// AUTO-GENERATED by content-engine/visual/scripts/tagVisualAi.ts — do not hand-edit.
// The AI draft for this family (planning-visual-pivot.md §4.3). To correct a
// cell, add it to the matching .overrides.ts file: overrides win per cell, and
// re-running the tagger never touches them.

import type { TagTable } from '../matrix.js'

export const TAGS: TagTable = {}
