import type { Item, ItemGroup } from './types.js'

// The visual item bank (planning-visual-pivot.md §5.1). Ids are permanent —
// see Item.id. Picked from `npm run visual:candidates`: globally familiar,
// one clear name each, nothing two players would name differently on sight.

const om = (id: string, name: string, group: ItemGroup, hex: string): Item => ({
  id,
  name,
  group,
  icon: { set: 'openmoji', hex },
})

export const ITEMS: Item[] = [
  // thing
  om('anchor', 'anchor', 'thing', '2693'),
  om('guitar', 'guitar', 'thing', '1F3B8'),
  om('violin', 'violin', 'thing', '1F3BB'),
  om('trumpet', 'trumpet', 'thing', '1F3BA'),
  om('drum', 'drum', 'thing', '1F941'),
  om('harp', 'harp', 'thing', '1FA89'),
  om('bell', 'bell', 'thing', '1F514'),
  om('headphones', 'headphones', 'thing', '1F3A7'),
  om('microphone', 'microphone', 'thing', '1F3A4'),
  om('mobile-phone', 'mobile phone', 'thing', '1F4F1'),
  om('battery', 'battery', 'thing', '1F50B'),
  om('electric-plug', 'electric plug', 'thing', '1F50C'),
  om('laptop', 'laptop', 'thing', '1F4BB'),
  om('television', 'television', 'thing', '1F4FA'),
  om('camera', 'camera', 'thing', '1F4F7'),
  om('candle', 'candle', 'thing', '1F56F'),
  om('light-bulb', 'light bulb', 'thing', '1F4A1'),
  om('flashlight', 'flashlight', 'thing', '1F526'),
  om('magnifying-glass', 'magnifying glass', 'thing', '1F50D'),
  om('book', 'book', 'thing', '1F4D5'),
  om('newspaper', 'newspaper', 'thing', '1F4F0'),
  om('coin', 'coin', 'thing', '1FA99'),
  om('treasure-chest', 'treasure chest', 'thing', '1FA8E'),
  om('credit-card', 'credit card', 'thing', '1F4B3'),
  om('envelope', 'envelope', 'thing', '2709'),
  om('cardboard-box', 'cardboard box', 'thing', '1F4E6'),
  om('pencil', 'pencil', 'thing', '270F'),
  om('paintbrush', 'paintbrush', 'thing', '1F58C'),
  om('crayon', 'crayon', 'thing', '1F58D'),
  om('paperclip', 'paperclip', 'thing', '1F4CE'),
  om('ruler', 'ruler', 'thing', '1F4CF'),
  om('scissors', 'scissors', 'thing', '2702'),
  om('key', 'key', 'thing', '1F511'),
  om('padlock', 'padlock', 'thing', '1F512'),
  om('hammer', 'hammer', 'thing', '1F528'),
  om('axe', 'axe', 'thing', '1FA93'),
  om('saw', 'saw', 'thing', '1FA9A'),
  om('wrench', 'wrench', 'thing', '1F527'),
  om('screwdriver', 'screwdriver', 'thing', '1FA9B'),
  om('magnet', 'magnet', 'thing', '1F9F2'),
  om('ladder', 'ladder', 'thing', '1FA9C'),
  om('shovel', 'shovel', 'thing', '1FA8F'),
  om('boomerang', 'boomerang', 'thing', '1FA83'),
  om('shield', 'shield', 'thing', '1F6E1'),
  om('test-tube', 'test tube', 'thing', '1F9EA'),
  om('microscope', 'microscope', 'thing', '1F52C'),
  om('syringe', 'syringe', 'thing', '1F489'),
  om('bandage', 'bandage', 'thing', '1FA79'),
  om('mirror', 'mirror', 'thing', '1FA9E'),
  om('bed', 'bed', 'thing', '1F6CF'),
  om('chair', 'chair', 'thing', '1FA91'),
  om('bathtub', 'bathtub', 'thing', '1F6C1'),
  om('broom', 'broom', 'thing', '1F9F9'),
  om('bucket', 'bucket', 'thing', '1FAA3'),
  om('soap', 'soap', 'thing', '1F9FC'),
  om('toothbrush', 'toothbrush', 'thing', '1FAA5'),
  om('sponge', 'sponge', 'thing', '1F9FD'),
  om('fire-extinguisher', 'fire extinguisher', 'thing', '1F9EF'),
  om('umbrella', 'umbrella', 'thing', '2602'),
  om('sunglasses', 'sunglasses', 'thing', '1F576'),
  om('necktie', 'necktie', 'thing', '1F454'),
  om('gloves', 'gloves', 'thing', '1F9E4'),
  om('socks', 'socks', 'thing', '1F9E6'),
  om('backpack', 'backpack', 'thing', '1F392'),
  om('running-shoe', 'running shoe', 'thing', '1F45F'),
  om('crown', 'crown', 'thing', '1F451'),
  om('ring', 'ring', 'thing', '1F48D'),
  om('balloon', 'balloon', 'thing', '1F388'),
  om('gift-box', 'gift box', 'thing', '1F381'),
  om('teddy-bear', 'teddy bear', 'thing', '1F9F8'),
  om('teapot', 'teapot', 'thing', '1FAD6'),
  om('spoon', 'spoon', 'thing', '1F944'),
  om('kitchen-knife', 'kitchen knife', 'thing', '1F52A'),
  om('jar', 'jar', 'thing', '1FAD9'),
  om('kite', 'kite', 'thing', '1FA81'),
  om('dice', 'dice', 'thing', '1F3B2'),
  om('soccer-ball', 'soccer ball', 'thing', '26BD'),
  om('ice-skate', 'ice skate', 'thing', '26F8'),
  om('trophy', 'trophy', 'thing', '1F3C6'),
  om('fishing-rod', 'fishing rod', 'thing', '1F3A3'),
  om('feather', 'feather', 'thing', '1FAB6'),
  om('seashell', 'seashell', 'thing', '1F41A'),
  om('ice-cube', 'ice cube', 'thing', '1F9CA'),
  om('life-ring', 'life ring', 'thing', '1F6DF'),

  // food
  om('banana', 'banana', 'food', '1F34C'),
  om('apple', 'apple', 'food', '1F34E'),
  om('lemon', 'lemon', 'food', '1F34B'),
  om('grapes', 'grapes', 'food', '1F347'),
  om('watermelon', 'watermelon', 'food', '1F349'),
  om('pineapple', 'pineapple', 'food', '1F34D'),
  om('strawberry', 'strawberry', 'food', '1F353'),
  om('coconut', 'coconut', 'food', '1F965'),
  om('tomato', 'tomato', 'food', '1F345'),
  om('carrot', 'carrot', 'food', '1F955'),
  om('potato', 'potato', 'food', '1F954'),
  om('corn-on-the-cob', 'corn on the cob', 'food', '1F33D'),
  om('broccoli', 'broccoli', 'food', '1F966'),
  om('onion', 'onion', 'food', '1F9C5'),
  om('peanuts', 'peanuts', 'food', '1F95C'),
  om('bread', 'bread', 'food', '1F35E'),
  om('cheese', 'cheese', 'food', '1F9C0'),
  om('egg', 'egg', 'food', '1F95A'),
  om('butter', 'butter', 'food', '1F9C8'),
  om('pizza', 'pizza', 'food', '1F355'),
  om('hamburger', 'hamburger', 'food', '1F354'),
  om('popcorn', 'popcorn', 'food', '1F37F'),
  om('doughnut', 'doughnut', 'food', '1F369'),
  om('cookie', 'cookie', 'food', '1F36A'),
  om('chocolate-bar', 'chocolate bar', 'food', '1F36B'),
  om('honey-pot', 'honey pot', 'food', '1F36F'),
  om('ice-cream-cone', 'ice cream cone', 'food', '1F366'),
  om('glass-of-milk', 'glass of milk', 'food', '1F95B'),

  // animal
  om('dog', 'dog', 'animal', '1F415'),
  om('cat', 'cat', 'animal', '1F408'),
  om('horse', 'horse', 'animal', '1F40E'),
  om('cow', 'cow', 'animal', '1F404'),
  om('pig', 'pig', 'animal', '1F416'),
  om('sheep', 'sheep', 'animal', '1F411'),
  om('camel', 'camel', 'animal', '1F42A'),
  om('giraffe', 'giraffe', 'animal', '1F992'),
  om('elephant', 'elephant', 'animal', '1F418'),
  om('mouse', 'mouse', 'animal', '1F401'),
  om('rabbit', 'rabbit', 'animal', '1F407'),
  om('bear', 'bear', 'animal', '1F43B'),
  om('chicken', 'chicken', 'animal', '1F414'),
  om('penguin', 'penguin', 'animal', '1F427'),
  om('duck', 'duck', 'animal', '1F986'),
  om('owl', 'owl', 'animal', '1F989'),
  om('frog', 'frog', 'animal', '1F438'),
  om('turtle', 'turtle', 'animal', '1F422'),
  om('snake', 'snake', 'animal', '1F40D'),
  om('whale', 'whale', 'animal', '1F40B'),
  om('fish', 'fish', 'animal', '1F41F'),
  om('shark', 'shark', 'animal', '1F988'),
  om('octopus', 'octopus', 'animal', '1F419'),
  om('crab', 'crab', 'animal', '1F980'),
  om('snail', 'snail', 'animal', '1F40C'),
  om('butterfly', 'butterfly', 'animal', '1F98B'),
  om('bee', 'bee', 'animal', '1F41D'),
  om('spider', 'spider', 'animal', '1F577'),

  // vehicle
  om('bicycle', 'bicycle', 'vehicle', '1F6B2'),
  om('car', 'car', 'vehicle', '1F697'),
  om('bus', 'bus', 'vehicle', '1F68C'),
  om('ambulance', 'ambulance', 'vehicle', '1F691'),
  om('fire-engine', 'fire engine', 'vehicle', '1F692'),
  om('tractor', 'tractor', 'vehicle', '1F69C'),
  om('motorcycle', 'motorcycle', 'vehicle', '1F3CD'),
  om('truck', 'truck', 'vehicle', '1F69A'),
  om('steam-train', 'steam train', 'vehicle', '1F682'),
  om('skateboard', 'skateboard', 'vehicle', '1F6F9'),
  om('sailboat', 'sailboat', 'vehicle', '26F5'),
  om('canoe', 'canoe', 'vehicle', '1F6F6'),
  om('airplane', 'airplane', 'vehicle', '2708'),
  om('helicopter', 'helicopter', 'vehicle', '1F681'),
  om('rocket', 'rocket', 'vehicle', '1F680'),

  // plant
  om('sunflower', 'sunflower', 'plant', '1F33B'),
  om('rose', 'rose', 'plant', '1F339'),
  om('tulip', 'tulip', 'plant', '1F337'),
  om('cactus', 'cactus', 'plant', '1F335'),
  om('palm-tree', 'palm tree', 'plant', '1F334'),
  om('tree', 'tree', 'plant', '1F333'),
  om('pine-tree', 'pine tree', 'plant', '1F332'),
  om('mushroom', 'mushroom', 'plant', '1F344'),
  om('four-leaf-clover', 'four-leaf clover', 'plant', '1F340'),
  om('maple-leaf', 'maple leaf', 'plant', '1F341'),
]
