import { CELLS, idsOf, type Cell, type TagRow, type TagTable } from './matrix.js'
import { FAMILY_BASIS } from './rules.js'
import type { Item, VisualRule } from './types.js'

// Pure prompt-building, response validation and consensus for the AI tagger
// (planning-visual-pivot.md §4.3). Kept apart from the script that calls the
// network so the part deciding what the model may assert is unit-tested — the
// same split as words/aiTagging.ts and scripts/tagWordsAi.ts.

export function buildRuleTaggingPrompt(rule: VisualRule, items: Item[]): string {
  const basis = [FAMILY_BASIS[rule.family], rule.basis].filter(Boolean).join(' ')
  return `You are labelling everyday things for a picture puzzle. For every item below,
decide whether this statement is true of it:

STATEMENT: "${rule.reveal}"

HOW TO JUDGE: ${basis}

ANSWERS:
- "yes": almost everyone would agree the statement is true of it.
- "no": almost everyone would agree the statement is false of it.
- "unsure": people could reasonably disagree, it depends on which version you
  picture, or you do not know.

When in doubt, answer "unsure". A wrong yes or no makes the puzzle mark a fair
answer wrong; "unsure" only means the item is left out of puzzles about this.

Answer every item exactly once, by its id.

ITEMS (id: name, group):
${items.map((i) => `${i.id}: ${i.name} (${i.group})`).join('\n')}`
}

/**
 * Validates one untrusted parsed-JSON response. Never throws. Ids we didn't ask
 * about and answers outside yes/no/unsure are dropped; an id answered twice in
 * different ways counts as unsure.
 */
export function parseRuleTaggingResponse(raw: unknown, requested: string[]): Map<string, Cell> {
  const asked = new Set(requested)
  const answers = new Map<string, Cell>()
  if (!Array.isArray(raw)) return answers
  for (const entry of raw) {
    if (typeof entry !== 'object' || entry === null) continue
    const { id, answer } = entry as Record<string, unknown>
    if (typeof id !== 'string' || !asked.has(id)) continue
    if (answer !== 'yes' && answer !== 'no' && answer !== 'unsure') continue
    const previous = answers.get(id)
    answers.set(id, previous === undefined || previous === answer ? answer : 'unsure')
  }
  return answers
}

/**
 * D3: a cell is yes or no only when every pass gave that answer. Disagreement,
 * or a pass that skipped the item, makes it unsure. An item no pass answered
 * stays untagged, so the next run asks again.
 */
export function consensus(passes: Map<string, Cell>[], ids: string[]): Map<string, Cell> {
  const cells = new Map<string, Cell>()
  for (const id of ids) {
    const answers = passes.map((p) => p.get(id))
    if (answers.every((a) => a === undefined)) continue
    const first = answers[0]
    cells.set(id, first !== undefined && answers.every((a) => a === first) ? first : 'unsure')
  }
  return cells
}

/** The items a rule still needs an AI answer for: not blocked, not drafted yet, not decided by a human. */
export function itemsToTag(
  ruleId: string,
  items: Item[],
  ai: TagTable,
  overrides: TagTable
): Item[] {
  const answered = new Set<string>()
  for (const row of [ai[ruleId], overrides[ruleId]]) {
    if (row) for (const cell of CELLS) for (const id of idsOf(row[cell])) answered.add(id)
  }
  return items.filter((i) => !i.blocked && !answered.has(i.id))
}

/** Adds new answers to a rule's AI row. */
export function mergeRow(row: TagRow | undefined, cells: Map<string, Cell>): TagRow {
  const merged: Record<Cell, string[]> = { yes: [], no: [], unsure: [] }
  for (const cell of CELLS) merged[cell].push(...idsOf(row?.[cell]))
  for (const [id, cell] of cells) merged[cell].push(id)
  return { yes: merged.yes.join(' '), no: merged.no.join(' '), unsure: merged.unsure.join(' ') }
}

/** The source of a `tags/<family>.ai.ts` file. Sorted, so a re-run only diffs what changed. */
export function renderAiTagFile(table: TagTable): string {
  const body = Object.keys(table)
    .sort()
    .map((ruleId) => {
      const lines = CELLS.map(
        (cell) => `    ${cell}: '${idsOf(table[ruleId][cell]).sort().join(' ')}',`
      )
      return [`  '${ruleId}': {`, ...lines, '  },'].join('\n')
    })
  return [
    '// AUTO-GENERATED by content-engine/visual/scripts/tagVisualAi.ts — do not hand-edit.',
    '// The AI draft for this family (planning-visual-pivot.md §4.3). To correct a',
    '// cell, add it to the matching .overrides.ts file: overrides win per cell, and',
    '// re-running the tagger never touches them.',
    '',
    "import type { TagTable } from '../matrix.js'",
    '',
    body.length === 0
      ? 'export const TAGS: TagTable = {}'
      : `export const TAGS: TagTable = {\n${body.join('\n')}\n}`,
    '',
  ].join('\n')
}
