import type { SeedWord } from './types'

// Phase 2/3 development fixture — NOT the production word bank.
// ~200 hand-picked common words, chosen to give every rule in
// rules/lexicalRules.ts plenty of real examples to work with, and to
// give the Phase 3 generator/validator enough raw material to find
// genuine rule collisions and decoys. See build-plan.md Phase 2 and the
// approved plan doc for the coverage targets behind this list.
//
// frequencyScore is a simple 3-tier hand-set scale for this seed list
// only (0.9 common / 0.6 moderate / 0.3 less common) — a real
// frequency-corpus integration is a later, separate content-ops phase.
const COMMON = 0.9
const MODERATE = 0.6
const LESS_COMMON = 0.3

function w(spelling: string, frequencyScore: number, partOfSpeech: SeedWord['partOfSpeech']): SeedWord {
  return { spelling, frequencyScore, partOfSpeech }
}

export const SEED_WORDS: SeedWord[] = [
  // --- doubled letter ---
  w('bubble', MODERATE, 'noun'),
  w('letter', COMMON, 'noun'),
  w('spoon', COMMON, 'noun'),
  w('apple', COMMON, 'noun'),
  w('follow', COMMON, 'verb'),
  w('dinner', COMMON, 'noun'),
  w('missing', COMMON, 'adjective'),
  w('arrow', MODERATE, 'noun'),
  w('cattle', MODERATE, 'noun'),
  w('kitten', COMMON, 'noun'),
  w('coffee', COMMON, 'noun'),
  w('dizzy', MODERATE, 'adjective'),
  w('puppy', COMMON, 'noun'),
  w('rabbit', COMMON, 'noun'),
  w('butter', COMMON, 'noun'),
  w('common', COMMON, 'adjective'),
  w('funny', COMMON, 'adjective'),
  w('happy', COMMON, 'adjective'),
  w('hello', COMMON, 'other'),
  w('mirror', COMMON, 'noun'),
  w('muddy', MODERATE, 'adjective'),
  w('needle', MODERATE, 'noun'),
  w('pillow', COMMON, 'noun'),
  w('silly', COMMON, 'adjective'),
  w('summer', COMMON, 'noun'),
  w('tunnel', MODERATE, 'noun'),
  w('wallet', COMMON, 'noun'),
  w('yellow', COMMON, 'adjective'),
  w('cheese', COMMON, 'noun'),
  w('ladder', MODERATE, 'noun'),

  // --- same start/end letter ---
  w('level', COMMON, 'adjective'),
  w('radar', MODERATE, 'noun'),
  w('noon', COMMON, 'noun'),
  w('area', COMMON, 'noun'),
  w('aroma', MODERATE, 'noun'),
  w('agenda', MODERATE, 'noun'),
  w('museum', COMMON, 'noun'),
  w('defend', COMMON, 'verb'),
  w('elude', LESS_COMMON, 'verb'),
  w('refer', MODERATE, 'verb'),
  w('stats', MODERATE, 'noun'),
  w('civic', LESS_COMMON, 'adjective'),
  w('gang', COMMON, 'noun'),
  w('tent', COMMON, 'noun'),
  w('pump', COMMON, 'noun'),

  // --- contains Q ---
  w('quiet', COMMON, 'adjective'),
  w('unique', COMMON, 'adjective'),
  w('mosque', MODERATE, 'noun'),
  w('quick', COMMON, 'adjective'),
  w('equal', COMMON, 'adjective'),
  w('request', COMMON, 'verb'),
  w('quality', COMMON, 'noun'),
  w('square', COMMON, 'noun'),
  w('question', COMMON, 'noun'),
  w('liquid', COMMON, 'noun'),
  w('queen', COMMON, 'noun'),
  w('quilt', MODERATE, 'noun'),

  // --- starts with a vowel ---
  w('otter', MODERATE, 'noun'),
  w('umbrella', COMMON, 'noun'),
  w('eagle', COMMON, 'noun'),
  w('igloo', MODERATE, 'noun'),
  w('orange', COMMON, 'noun'),
  w('elephant', COMMON, 'noun'),
  w('island', COMMON, 'noun'),
  w('oyster', MODERATE, 'noun'),
  w('acorn', MODERATE, 'noun'),
  w('engine', COMMON, 'noun'),
  w('opera', MODERATE, 'noun'),
  w('item', COMMON, 'noun'),
  w('ocean', COMMON, 'noun'),
  w('autumn', COMMON, 'noun'),
  w('ember', LESS_COMMON, 'noun'),
  w('iron', COMMON, 'noun'),
  w('oval', MODERATE, 'adjective'),
  w('ugly', COMMON, 'adjective'),
  w('anchor', MODERATE, 'noun'),
  w('echo', COMMON, 'noun'),
  w('ivory', LESS_COMMON, 'noun'),
  w('onion', COMMON, 'noun'),
  w('avenue', COMMON, 'noun'),

  // --- exactly two vowels ---
  w('table', COMMON, 'noun'),
  w('little', COMMON, 'adjective'),
  w('middle', COMMON, 'noun'),
  w('puzzle', COMMON, 'noun'),
  w('purple', COMMON, 'adjective'),
  w('bottle', COMMON, 'noun'),
  w('temple', MODERATE, 'noun'),
  w('circle', COMMON, 'noun'),
  w('gentle', COMMON, 'adjective'),
  w('castle', COMMON, 'noun'),
  w('pickle', MODERATE, 'noun'),
  w('candle', COMMON, 'noun'),
  w('handle', COMMON, 'verb'),
  w('bundle', MODERATE, 'noun'),
  w('tackle', MODERATE, 'verb'),
  w('wobble', MODERATE, 'verb'),
  w('marble', MODERATE, 'noun'),
  w('planet', COMMON, 'noun'),
  w('basket', COMMON, 'noun'),
  w('magnet', COMMON, 'noun'),
  w('pocket', COMMON, 'noun'),
  w('ticket', COMMON, 'noun'),
  w('rocket', COMMON, 'noun'),

  // --- no adjacent vowels (consonant-heavy words) ---
  w('cat', COMMON, 'noun'),
  w('dog', COMMON, 'noun'),
  w('plan', COMMON, 'noun'),
  w('desk', COMMON, 'noun'),
  w('lamp', COMMON, 'noun'),
  w('trust', COMMON, 'noun'),
  w('black', COMMON, 'adjective'),
  w('spring', COMMON, 'noun'),
  w('gift', COMMON, 'noun'),
  w('dust', COMMON, 'noun'),
  w('milk', COMMON, 'noun'),
  w('silk', MODERATE, 'noun'),
  w('chess', COMMON, 'noun'),
  w('class', COMMON, 'noun'),
  w('grass', COMMON, 'noun'),
  w('brush', COMMON, 'noun'),
  w('crust', MODERATE, 'noun'),
  w('blend', MODERATE, 'verb'),
  w('spend', COMMON, 'verb'),
  w('trend', COMMON, 'noun'),
  w('stamp', COMMON, 'noun'),
  w('plant', COMMON, 'noun'),
  w('print', COMMON, 'verb'),
  w('frost', MODERATE, 'noun'),
  w('drink', COMMON, 'verb'),

  // --- third letter is a vowel ---
  w('piano', COMMON, 'noun'),
  w('poetic', LESS_COMMON, 'adjective'),
  w('react', COMMON, 'verb'),
  w('beacon', MODERATE, 'noun'),
  w('coast', COMMON, 'noun'),
  w('float', COMMON, 'verb'),
  w('cream', COMMON, 'noun'),
  w('bread', COMMON, 'noun'),
  w('steam', COMMON, 'noun'),
  w('cloud', COMMON, 'noun'),
  w('proud', COMMON, 'adjective'),
  w('great', COMMON, 'adjective'),
  w('dream', COMMON, 'noun'),
  w('brain', COMMON, 'noun'),
  w('chair', COMMON, 'noun'),
  w('point', COMMON, 'noun'),
  w('spoil', MODERATE, 'verb'),
  w('sound', COMMON, 'noun'),
  w('round', COMMON, 'adjective'),
  w('cheat', COMMON, 'verb'),
  w('wheat', MODERATE, 'noun'),

  // --- hides A-C-E in order (subsequence) ---
  w('space', COMMON, 'noun'),
  w('advice', COMMON, 'noun'),
  w('distance', COMMON, 'noun'),
  w('peace', COMMON, 'noun'),
  w('trace', MODERATE, 'verb'),
  w('replace', COMMON, 'verb'),
  w('embrace', MODERATE, 'verb'),
  w('surface', COMMON, 'noun'),
  w('package', COMMON, 'noun'),
  w('palace', MODERATE, 'noun'),
  w('menace', LESS_COMMON, 'noun'),
  w('terrace', LESS_COMMON, 'noun'),
  w('furnace', MODERATE, 'noun'),
  w('race', COMMON, 'noun'),
  w('face', COMMON, 'noun'),
  w('lace', MODERATE, 'noun'),
  w('pace', MODERATE, 'noun'),
  w('place', COMMON, 'noun'),

  // --- hides a number word inside it ---
  w('money', COMMON, 'noun'),
  w('honest', COMMON, 'adjective'),
  w('stone', COMMON, 'noun'),
  w('atone', LESS_COMMON, 'verb'),
  w('prone', MODERATE, 'adjective'),
  w('cyclone', LESS_COMMON, 'noun'),
  w('network', COMMON, 'noun'),
  w('twofold', LESS_COMMON, 'adjective'),
  w('sixteen', COMMON, 'noun'),
  w('sixty', COMMON, 'noun'),
  w('often', COMMON, 'adverb'),
  w('listen', COMMON, 'verb'),
  w('mitten', MODERATE, 'noun'),
  w('rotten', COMMON, 'adjective'),
  w('canine', LESS_COMMON, 'adjective'),
  w('feminine', MODERATE, 'adjective'),

  // --- general-purpose filler (padding + extra decoy raw material) ---
  w('garden', COMMON, 'noun'),
  w('window', COMMON, 'noun'),
  w('pencil', COMMON, 'noun'),
  w('forest', COMMON, 'noun'),
  w('river', COMMON, 'noun'),
  w('mountain', COMMON, 'noun'),
  w('bridge', COMMON, 'noun'),
  w('jacket', COMMON, 'noun'),
  w('blanket', COMMON, 'noun'),
  w('thunder', COMMON, 'noun'),
  w('whisper', MODERATE, 'verb'),
  w('mystery', COMMON, 'noun'),
  w('journey', COMMON, 'noun'),
  w('picture', COMMON, 'noun'),
  w('kitchen', COMMON, 'noun'),
  w('library', COMMON, 'noun'),
  w('calendar', COMMON, 'noun'),
  w('volcano', MODERATE, 'noun'),
  w('dolphin', MODERATE, 'noun'),
  w('penguin', MODERATE, 'noun'),
  w('hamster', LESS_COMMON, 'noun'),
  w('giraffe', MODERATE, 'noun'),
]
