import type { SeedWord } from './types'

// Phase 2/3 development fixture — NOT the production word bank.
// ~400 hand-picked common words (grown from an original ~230 — see the
// approved plan doc on generator bias/repetition), chosen to give every
// rule in rules/lexicalRules.ts and rules/semanticRules.ts a large enough
// eligible pool that one puzzle's clue set + guest pool doesn't consume a
// large fraction of it, which is what was causing frequent word-overlap
// across generated puzzles for the thinnest rules. See build-plan.md
// Phase 2 and the approved plan doc for the coverage targets behind this
// list.
//
// frequencyScore is a simple 3-tier hand-set scale for this seed list
// only (0.9 common / 0.6 moderate / 0.3 less common) — a real
// frequency-corpus integration is a later, separate content-ops phase.
const COMMON = 0.9
const MODERATE = 0.6
const LESS_COMMON = 0.3

function w(
  spelling: string,
  frequencyScore: number,
  partOfSpeech: SeedWord['partOfSpeech'],
  tags?: string[]
): SeedWord {
  return { spelling, frequencyScore, partOfSpeech, tags }
}

export const SEED_WORDS: SeedWord[] = [
  // --- doubled letter ---
  w('bubble', MODERATE, 'noun'),
  w('letter', COMMON, 'noun'),
  w('spoon', COMMON, 'noun'),
  w('apple', COMMON, 'noun', ['category:fruit']),
  w('follow', COMMON, 'verb'),
  w('dinner', COMMON, 'noun'),
  w('missing', COMMON, 'adjective'),
  w('arrow', MODERATE, 'noun'),
  w('cattle', MODERATE, 'noun'),
  w('kitten', COMMON, 'noun', ['category:animal']),
  w('coffee', COMMON, 'noun'),
  w('dizzy', MODERATE, 'adjective'),
  w('puppy', COMMON, 'noun', ['category:animal']),
  w('rabbit', COMMON, 'noun', ['category:animal']),
  w('butter', COMMON, 'noun'),
  w('common', COMMON, 'adjective'),
  w('funny', COMMON, 'adjective'),
  w('happy', COMMON, 'adjective'),
  w('hello', COMMON, 'other'),
  w('mirror', COMMON, 'noun'),
  w('muddy', MODERATE, 'adjective'),
  w('needle', MODERATE, 'noun', ['category:tool']),
  w('pillow', COMMON, 'noun'),
  w('silly', COMMON, 'adjective'),
  w('summer', COMMON, 'noun'),
  w('tunnel', MODERATE, 'noun'),
  w('wallet', COMMON, 'noun'),
  w('yellow', COMMON, 'adjective'),
  w('cheese', COMMON, 'noun'),
  w('ladder', MODERATE, 'noun', ['category:tool']),

  // --- same start/end letter ---
  w('level', COMMON, 'adjective'),
  w('radar', MODERATE, 'noun'),
  w('noon', COMMON, 'noun'),
  w('area', COMMON, 'noun'),
  w('aroma', MODERATE, 'noun'),
  w('agenda', MODERATE, 'noun'),
  w('museum', COMMON, 'noun', ['category:building']),
  w('defend', COMMON, 'verb'),
  w('elude', LESS_COMMON, 'verb'),
  w('refer', MODERATE, 'verb'),
  w('stats', MODERATE, 'noun'),
  w('civic', LESS_COMMON, 'adjective'),
  w('gang', COMMON, 'noun'),
  w('tent', COMMON, 'noun'),
  w('pump', COMMON, 'noun'),

  // --- contains Q ---
  w('quiet', COMMON, 'adjective'),
  w('unique', COMMON, 'adjective'),
  w('mosque', MODERATE, 'noun', ['category:building']),
  w('quick', COMMON, 'adjective'),
  w('equal', COMMON, 'adjective'),
  w('request', COMMON, 'verb'),
  w('quality', COMMON, 'noun'),
  w('square', COMMON, 'noun', ['category:tool']),
  w('question', COMMON, 'noun'),
  w('liquid', COMMON, 'noun'),
  w('queen', COMMON, 'noun'),
  w('quilt', MODERATE, 'noun'),

  // --- starts with a vowel ---
  w('otter', MODERATE, 'noun', ['category:animal']),
  w('umbrella', COMMON, 'noun'),
  w('eagle', COMMON, 'noun', ['category:bird']),
  w('igloo', MODERATE, 'noun'),
  w('orange', COMMON, 'noun', ['category:fruit']),
  w('elephant', COMMON, 'noun', ['category:animal']),
  w('island', COMMON, 'noun'),
  w('oyster', MODERATE, 'noun'),
  w('acorn', MODERATE, 'noun'),
  w('engine', COMMON, 'noun'),
  w('opera', MODERATE, 'noun'),
  w('item', COMMON, 'noun'),
  w('ocean', COMMON, 'noun'),
  w('autumn', COMMON, 'noun'),
  w('ember', LESS_COMMON, 'noun'),
  w('iron', COMMON, 'noun'),
  w('oval', MODERATE, 'adjective'),
  w('ugly', COMMON, 'adjective'),
  w('anchor', MODERATE, 'noun'),
  w('echo', COMMON, 'noun'),
  w('ivory', LESS_COMMON, 'noun'),
  w('onion', COMMON, 'noun'),
  w('avenue', COMMON, 'noun'),

  // --- exactly two vowels ---
  w('table', COMMON, 'noun'),
  w('little', COMMON, 'adjective'),
  w('middle', COMMON, 'noun'),
  w('puzzle', COMMON, 'noun'),
  w('purple', COMMON, 'adjective'),
  w('bottle', COMMON, 'noun'),
  w('temple', MODERATE, 'noun'),
  w('circle', COMMON, 'noun'),
  w('gentle', COMMON, 'adjective'),
  w('castle', COMMON, 'noun', ['category:building']),
  w('pickle', MODERATE, 'noun'),
  w('candle', COMMON, 'noun'),
  w('handle', COMMON, 'verb'),
  w('bundle', MODERATE, 'noun'),
  w('tackle', MODERATE, 'verb'),
  w('wobble', MODERATE, 'verb'),
  w('marble', MODERATE, 'noun'),
  w('planet', COMMON, 'noun'),
  w('basket', COMMON, 'noun'),
  w('magnet', COMMON, 'noun'),
  w('pocket', COMMON, 'noun'),
  w('ticket', COMMON, 'noun'),
  w('rocket', COMMON, 'noun', ['category:vehicle']),

  // --- no adjacent vowels (consonant-heavy words) ---
  w('cat', COMMON, 'noun'),
  w('dog', COMMON, 'noun', ['category:animal']),
  w('plan', COMMON, 'noun'),
  w('desk', COMMON, 'noun'),
  w('lamp', COMMON, 'noun'),
  w('trust', COMMON, 'noun'),
  w('black', COMMON, 'adjective'),
  w('spring', COMMON, 'noun'),
  w('gift', COMMON, 'noun'),
  w('dust', COMMON, 'noun'),
  w('milk', COMMON, 'noun'),
  w('silk', MODERATE, 'noun'),
  w('chess', COMMON, 'noun'),
  w('class', COMMON, 'noun'),
  w('grass', COMMON, 'noun'),
  w('brush', COMMON, 'noun'),
  w('crust', MODERATE, 'noun'),
  w('blend', MODERATE, 'verb'),
  w('spend', COMMON, 'verb'),
  w('trend', COMMON, 'noun'),
  w('stamp', COMMON, 'noun', ['category:tool']),
  w('plant', COMMON, 'noun'),
  w('print', COMMON, 'verb'),
  w('frost', MODERATE, 'noun'),
  w('drink', COMMON, 'verb'),

  // --- third letter is a vowel ---
  w('piano', COMMON, 'noun'),
  w('poetic', LESS_COMMON, 'adjective'),
  w('react', COMMON, 'verb'),
  w('beacon', MODERATE, 'noun'),
  w('coast', COMMON, 'noun'),
  w('float', COMMON, 'verb', ['category:tool']),
  w('cream', COMMON, 'noun'),
  w('bread', COMMON, 'noun'),
  w('steam', COMMON, 'noun'),
  w('cloud', COMMON, 'noun'),
  w('proud', COMMON, 'adjective'),
  w('great', COMMON, 'adjective'),
  w('dream', COMMON, 'noun'),
  w('brain', COMMON, 'noun', ['category:body-part']),
  w('chair', COMMON, 'noun'),
  w('point', COMMON, 'noun'),
  w('spoil', MODERATE, 'verb'),
  w('sound', COMMON, 'noun'),
  w('round', COMMON, 'adjective'),
  w('cheat', COMMON, 'verb'),
  w('wheat', MODERATE, 'noun'),

  // --- hides A-C-E in order (subsequence) ---
  w('space', COMMON, 'noun'),
  w('advice', COMMON, 'noun'),
  w('distance', COMMON, 'noun'),
  w('peace', COMMON, 'noun'),
  w('trace', MODERATE, 'verb'),
  w('replace', COMMON, 'verb'),
  w('embrace', MODERATE, 'verb'),
  w('surface', COMMON, 'noun'),
  w('package', COMMON, 'noun'),
  w('palace', MODERATE, 'noun', ['category:building']),
  w('menace', LESS_COMMON, 'noun'),
  w('terrace', LESS_COMMON, 'noun'),
  w('furnace', MODERATE, 'noun'),
  w('race', COMMON, 'noun'),
  w('face', COMMON, 'noun', ['category:body-part']),
  w('lace', MODERATE, 'noun'),
  w('pace', MODERATE, 'noun'),
  w('place', COMMON, 'noun'),

  // --- hides a number word inside it ---
  w('money', COMMON, 'noun'),
  w('honest', COMMON, 'adjective'),
  w('stone', COMMON, 'noun'),
  w('atone', LESS_COMMON, 'verb'),
  w('prone', MODERATE, 'adjective'),
  w('cyclone', LESS_COMMON, 'noun'),
  w('network', COMMON, 'noun'),
  w('twofold', LESS_COMMON, 'adjective'),
  w('sixteen', COMMON, 'noun'),
  w('sixty', COMMON, 'noun'),
  w('often', COMMON, 'adverb'),
  w('listen', COMMON, 'verb'),
  w('mitten', MODERATE, 'noun'),
  w('rotten', COMMON, 'adjective'),
  w('canine', LESS_COMMON, 'adjective'),
  w('feminine', MODERATE, 'adjective'),

  // --- general-purpose filler (padding + extra decoy raw material) ---
  w('garden', COMMON, 'noun'),
  w('window', COMMON, 'noun'),
  w('pencil', COMMON, 'noun'),
  w('forest', COMMON, 'noun'),
  w('river', COMMON, 'noun'),
  w('mountain', COMMON, 'noun'),
  w('bridge', COMMON, 'noun'),
  w('jacket', COMMON, 'noun'),
  w('blanket', COMMON, 'noun'),
  w('thunder', COMMON, 'noun'),
  w('whisper', MODERATE, 'verb'),
  w('mystery', COMMON, 'noun'),
  w('journey', COMMON, 'noun'),
  w('picture', COMMON, 'noun'),
  w('kitchen', COMMON, 'noun'),
  w('library', COMMON, 'noun', ['category:building']),
  w('calendar', COMMON, 'noun'),
  w('volcano', MODERATE, 'noun'),
  w('dolphin', MODERATE, 'noun', ['category:animal']),
  w('penguin', MODERATE, 'noun', ['category:bird']),
  w('hamster', LESS_COMMON, 'noun', ['category:animal']),
  w('giraffe', MODERATE, 'noun', ['category:animal']),

  // --- semantic category words (build-plan.md Phase 10.5 §2, Step 5 prep) ---
  // Added so every reviewed category tag has enough real words to clear the
  // generator's clueCountIn floor plus a non-degenerate guest-pool buffer,
  // not just the bare minimum surfaced by Step 3's automated tagging pass.
  w('hammer', COMMON, 'noun', ['category:tool']),
  w('wrench', MODERATE, 'noun', ['category:tool']),
  w('shovel', MODERATE, 'noun', ['category:tool']),
  w('cabin', MODERATE, 'noun', ['category:building']),
  w('cottage', MODERATE, 'noun', ['category:building']),
  w('tower', COMMON, 'noun', ['category:building']),
  w('barn', COMMON, 'noun', ['category:building']),
  w('banana', COMMON, 'noun', ['category:fruit']),
  w('grape', COMMON, 'noun', ['category:fruit']),
  w('mango', MODERATE, 'noun', ['category:fruit']),
  w('lemon', COMMON, 'noun', ['category:fruit']),
  w('cherry', COMMON, 'noun', ['category:fruit']),
  w('car', COMMON, 'noun', ['category:vehicle']),
  w('train', COMMON, 'noun', ['category:vehicle']),
  w('bicycle', COMMON, 'noun', ['category:vehicle']),
  w('canoe', MODERATE, 'noun', ['category:vehicle']),
  w('tractor', MODERATE, 'noun', ['category:vehicle']),
  w('scooter', MODERATE, 'noun', ['category:vehicle']),
  w('sparrow', MODERATE, 'noun', ['category:bird']),
  w('owl', COMMON, 'noun', ['category:bird']),
  w('robin', MODERATE, 'noun', ['category:bird']),
  w('parrot', MODERATE, 'noun', ['category:bird']),
  w('falcon', MODERATE, 'noun', ['category:bird']),
  w('elbow', COMMON, 'noun', ['category:body-part']),
  w('ankle', COMMON, 'noun', ['category:body-part']),
  w('wrist', COMMON, 'noun', ['category:body-part']),
  w('thumb', COMMON, 'noun', ['category:body-part']),
  w('shoulder', COMMON, 'noun', ['category:body-part']),

  // --- more same-start/end-letter words (approved plan: grow thin rule pools) ---
  w('eye', COMMON, 'noun'),
  w('dad', COMMON, 'noun'),
  w('mom', COMMON, 'noun'),
  w('pop', COMMON, 'noun'),
  w('bib', MODERATE, 'noun'),
  w('bathtub', COMMON, 'noun'),
  w('bulb', COMMON, 'noun'),
  w('comic', COMMON, 'adjective'),
  w('critic', MODERATE, 'noun'),
  w('classic', COMMON, 'adjective'),
  w('cosmic', MODERATE, 'adjective'),
  w('diamond', COMMON, 'noun'),
  w('dried', COMMON, 'adjective'),
  w('extreme', COMMON, 'adjective'),
  w('elite', MODERATE, 'noun'),
  w('arena', COMMON, 'noun'),
  w('aura', MODERATE, 'noun'),
  w('algebra', MODERATE, 'noun'),
  w('gong', MODERATE, 'noun'),
  w('gig', MODERATE, 'noun'),
  w('hush', MODERATE, 'noun'),
  w('hutch', LESS_COMMON, 'noun'),
  w('harsh', COMMON, 'adjective'),
  w('nylon', MODERATE, 'noun'),
  w('kayak', MODERATE, 'noun', ['category:vehicle']),
  w('tidbit', LESS_COMMON, 'noun'),
  w('toast', COMMON, 'noun'),
  w('transit', MODERATE, 'noun'),
  w('tacit', LESS_COMMON, 'adjective'),
  w('target', COMMON, 'noun'),
  w('trout', MODERATE, 'noun', ['category:animal']),

  // --- more contains-Q words ---
  w('quirky', MODERATE, 'adjective'),
  w('quote', COMMON, 'noun'),
  w('quarter', COMMON, 'noun'),
  w('squash', COMMON, 'noun'),
  w('squad', COMMON, 'noun'),
  w('squeeze', COMMON, 'verb'),
  w('inquiry', MODERATE, 'noun'),
  w('equator', MODERATE, 'noun'),
  w('technique', COMMON, 'noun'),
  w('antique', COMMON, 'adjective'),
  w('opaque', LESS_COMMON, 'adjective'),
  w('mosquito', COMMON, 'noun'),
  w('quarrel', MODERATE, 'noun'),
  w('quench', MODERATE, 'verb'),
  w('acquire', COMMON, 'verb'),
  w('frequent', COMMON, 'adjective'),
  w('equipment', COMMON, 'noun'),
  w('banquet', MODERATE, 'noun'),
  w('bouquet', MODERATE, 'noun'),
  w('conquer', COMMON, 'verb'),
  w('quiz', COMMON, 'noun'),
  w('quart', LESS_COMMON, 'noun'),
  w('earthquake', COMMON, 'noun'),
  w('squirrel', COMMON, 'noun', ['category:animal']),
  w('squid', MODERATE, 'noun', ['category:animal']),

  // --- more hidden-number words (targets: one, two, six, ten, nine) ---
  w('alone', COMMON, 'adjective'),
  w('phone', COMMON, 'noun'),
  w('throne', COMMON, 'noun'),
  w('someone', COMMON, 'other'),
  w('anyone', COMMON, 'other'),
  w('bone', COMMON, 'noun'),
  w('cone', COMMON, 'noun'),
  w('tone', COMMON, 'noun'),
  w('zone', COMMON, 'noun'),
  w('drone', MODERATE, 'noun'),
  w('clone', MODERATE, 'noun'),
  w('telephone', COMMON, 'noun'),
  w('honey', COMMON, 'noun'),
  w('backbone', COMMON, 'noun'),
  w('lonely', COMMON, 'adjective'),
  w('two', COMMON, 'other'),
  w('twosome', LESS_COMMON, 'noun'),
  w('six', COMMON, 'other'),
  w('tender', COMMON, 'adjective'),
  w('tennis', COMMON, 'noun'),
  w('attend', COMMON, 'verb'),
  w('attention', COMMON, 'noun'),
  w('extend', COMMON, 'verb'),
  w('intend', COMMON, 'verb'),
  w('intent', MODERATE, 'noun'),
  w('pretend', COMMON, 'verb'),
  w('sentence', COMMON, 'noun'),
  w('tenant', MODERATE, 'noun'),
  w('ten', COMMON, 'other'),
  w('nine', COMMON, 'other'),
  w('ninety', COMMON, 'other'),

  // --- more subsequence-ace words (A, C, E in order) ---
  w('advance', COMMON, 'verb'),
  w('acre', MODERATE, 'noun'),
  w('sacred', COMMON, 'adjective'),
  w('vacate', MODERATE, 'verb'),
  w('aches', COMMON, 'noun'),
  w('backache', MODERATE, 'noun'),
  w('advocate', MODERATE, 'noun'),
  w('sacrifice', COMMON, 'noun'),
  w('acceptance', MODERATE, 'noun'),
  w('grace', COMMON, 'noun'),
  w('brace', MODERATE, 'noun'),
  w('bracelet', COMMON, 'noun'),
  w('vaccine', COMMON, 'noun'),
  w('spacecraft', COMMON, 'noun', ['category:vehicle']),
  w('raceway', LESS_COMMON, 'noun'),
  w('peaceful', COMMON, 'adjective'),
  w('graceful', COMMON, 'adjective'),
  w('accent', COMMON, 'noun'),

  // --- semantic category growth (approved plan: 7-8 words/category -> ~18-20) ---
  w('fox', COMMON, 'noun', ['category:animal']),
  w('wolf', COMMON, 'noun', ['category:animal']),
  w('tiger', COMMON, 'noun', ['category:animal']),
  w('lion', COMMON, 'noun', ['category:animal']),
  w('deer', COMMON, 'noun', ['category:animal']),
  w('zebra', COMMON, 'noun', ['category:animal']),
  w('koala', COMMON, 'noun', ['category:animal']),
  w('kangaroo', COMMON, 'noun', ['category:animal']),
  w('raccoon', MODERATE, 'noun', ['category:animal']),
  w('monkey', COMMON, 'noun', ['category:animal']),

  w('peach', COMMON, 'noun', ['category:fruit']),
  w('pear', COMMON, 'noun', ['category:fruit']),
  w('plum', COMMON, 'noun', ['category:fruit']),
  w('melon', COMMON, 'noun', ['category:fruit']),
  w('kiwi', MODERATE, 'noun', ['category:fruit']),
  w('pineapple', COMMON, 'noun', ['category:fruit']),
  w('strawberry', COMMON, 'noun', ['category:fruit']),
  w('blueberry', COMMON, 'noun', ['category:fruit']),
  w('raspberry', COMMON, 'noun', ['category:fruit']),
  w('coconut', COMMON, 'noun', ['category:fruit']),
  w('apricot', MODERATE, 'noun', ['category:fruit']),
  w('fig', MODERATE, 'noun', ['category:fruit']),

  w('truck', COMMON, 'noun', ['category:vehicle']),
  w('motorcycle', COMMON, 'noun', ['category:vehicle']),
  w('bus', COMMON, 'noun', ['category:vehicle']),
  w('airplane', COMMON, 'noun', ['category:vehicle']),
  w('helicopter', COMMON, 'noun', ['category:vehicle']),
  w('boat', COMMON, 'noun', ['category:vehicle']),
  w('ship', COMMON, 'noun', ['category:vehicle']),
  w('van', COMMON, 'noun', ['category:vehicle']),
  w('taxi', COMMON, 'noun', ['category:vehicle']),
  w('submarine', COMMON, 'noun', ['category:vehicle']),
  w('sled', MODERATE, 'noun', ['category:vehicle']),
  w('wagon', COMMON, 'noun', ['category:vehicle']),

  w('house', COMMON, 'noun', ['category:building']),
  w('school', COMMON, 'noun', ['category:building']),
  w('hospital', COMMON, 'noun', ['category:building']),
  w('hotel', COMMON, 'noun', ['category:building']),
  w('stadium', COMMON, 'noun', ['category:building']),
  w('theater', COMMON, 'noun', ['category:building']),
  w('garage', COMMON, 'noun', ['category:building']),
  w('warehouse', COMMON, 'noun', ['category:building']),
  w('skyscraper', COMMON, 'noun', ['category:building']),
  w('lighthouse', COMMON, 'noun', ['category:building']),
  w('mansion', COMMON, 'noun', ['category:building']),

  w('hawk', COMMON, 'noun', ['category:bird']),
  w('peacock', MODERATE, 'noun', ['category:bird']),
  w('flamingo', MODERATE, 'noun', ['category:bird']),
  w('swan', COMMON, 'noun', ['category:bird']),
  w('duck', COMMON, 'noun', ['category:bird']),
  w('goose', COMMON, 'noun', ['category:bird']),
  w('crow', COMMON, 'noun', ['category:bird']),
  w('raven', MODERATE, 'noun', ['category:bird']),
  w('pigeon', COMMON, 'noun', ['category:bird']),
  w('seagull', MODERATE, 'noun', ['category:bird']),
  w('woodpecker', MODERATE, 'noun', ['category:bird']),
  w('ostrich', MODERATE, 'noun', ['category:bird']),

  w('screwdriver', COMMON, 'noun', ['category:tool']),
  w('saw', COMMON, 'noun', ['category:tool']),
  w('drill', COMMON, 'noun', ['category:tool']),
  w('pliers', MODERATE, 'noun', ['category:tool']),
  w('chisel', LESS_COMMON, 'noun', ['category:tool']),
  w('axe', COMMON, 'noun', ['category:tool']),
  w('rake', COMMON, 'noun', ['category:tool']),
  w('scissors', COMMON, 'noun', ['category:tool']),
  w('stapler', MODERATE, 'noun', ['category:tool']),
  w('mallet', LESS_COMMON, 'noun', ['category:tool']),

  w('leg', COMMON, 'noun', ['category:body-part']),
  w('hand', COMMON, 'noun', ['category:body-part']),
  w('finger', COMMON, 'noun', ['category:body-part']),
  w('knee', COMMON, 'noun', ['category:body-part']),
  w('spine', MODERATE, 'noun', ['category:body-part']),
  w('skull', MODERATE, 'noun', ['category:body-part']),
  w('rib', MODERATE, 'noun', ['category:body-part']),
  w('lung', MODERATE, 'noun', ['category:body-part']),
  w('heart', COMMON, 'noun', ['category:body-part']),
  w('stomach', COMMON, 'noun', ['category:body-part']),
  w('neck', COMMON, 'noun', ['category:body-part']),
  w('chest', COMMON, 'noun', ['category:body-part']),
]
