/**
 * Human-reviewed tags for words that don't carry their own (mainly
 * BULK_SEED_WORDS, which is machine-generated with no tags at all — see
 * expandWordBank.ts). Kept as a separate overlay file, applied by
 * buildWordBank(), specifically so re-running the bulk-generation script can
 * never clobber reviewed data, mirroring why bulkSeedWords.ts and
 * seedWords.ts are also kept separate.
 *
 * Reviewed 2026-08-30 from content-engine/output/suggestedTags.md, the
 * output of re-running `tagWords.ts` (Phase 10.5 §2) against the expanded
 * 5,000-word bank (Phase 10.6). 379 raw suggestions reviewed down to the
 * entries below, using the same "is this the word's clearest, most common
 * everyday sense" test the original Step 4 review established (e.g.
 * dropping `temple`/`bridge` again here for the same reason as before —
 * real matches, wrong dominant sense). Categories varied a lot in
 * signal-to-noise: `body-part` alone had 111 raw suggestions, cut to 46
 * genuinely clean ones. All `property:*` targets except `kitchen` stayed
 * thin or came back empty (`round` had zero usable matches — every hit was
 * "a round of boxing," not "round-shaped") — the idiom-noise problem
 * documented in Step 4 evidently isn't specific to the smaller word bank.
 */
export const TAG_OVERRIDES: Record<string, string[]> = {
  // category:animal
  kitten: ['category:animal'],
  puppy: ['category:animal'],
  oyster: ['category:animal'],
  dog: ['category:animal'],
  parrot: ['category:animal', 'category:bird'],
  fish: ['category:animal'],
  bird: ['category:animal'],
  kitty: ['category:animal'],
  chick: ['category:animal'],
  bug: ['category:animal'],
  frog: ['category:animal'],
  lamb: ['category:animal'],
  worm: ['category:animal'],
  spider: ['category:animal'],

  // category:bird
  eagle: ['category:bird'],
  penguin: ['category:bird'],
  sparrow: ['category:bird'],
  owl: ['category:bird'],
  robin: ['category:bird'],
  falcon: ['category:bird'],
  hawk: ['category:bird'],
  flamingo: ['category:bird'],
  swan: ['category:bird'],
  duck: ['category:bird'],
  goose: ['category:bird'],
  crow: ['category:bird'],
  raven: ['category:bird'],
  pigeon: ['category:bird'],
  woodpecker: ['category:bird'],
  ostrich: ['category:bird'],
  chicken: ['category:bird'],
  crane: ['category:bird'],
  jay: ['category:bird'],

  // category:building
  mosque: ['category:building'],
  castle: ['category:building'],
  palace: ['category:building'],
  library: ['category:building'],
  cabin: ['category:building'],
  cottage: ['category:building'],
  barn: ['category:building'],
  house: ['category:building'],
  school: ['category:building'],
  hospital: ['category:building'],
  hotel: ['category:building'],
  theater: ['category:building'],
  garage: ['category:building'],
  skyscraper: ['category:building'],
  mansion: ['category:building'],
  church: ['category:building'],
  hall: ['category:building'],
  restaurant: ['category:building'],
  ruin: ['category:building'],
  casino: ['category:building'],
  motel: ['category:building'],
  clinic: ['category:building'],
  stable: ['category:building'],
  diner: ['category:building'],
  theatre: ['category:building'],
  shed: ['category:building'],
  coop: ['category:building'],
  morgue: ['category:building'],
  inn: ['category:building'],
  residence: ['category:building'],
  chapel: ['category:building'],

  // category:fruit
  apple: ['category:fruit'],
  orange: ['category:fruit'],
  banana: ['category:fruit'],
  grape: ['category:fruit'],
  mango: ['category:fruit'],
  lemon: ['category:fruit'],
  cherry: ['category:fruit'],
  peach: ['category:fruit'],
  pear: ['category:fruit'],
  plum: ['category:fruit'],
  melon: ['category:fruit'],
  kiwi: ['category:fruit'],
  pineapple: ['category:fruit'],
  strawberry: ['category:fruit'],
  blueberry: ['category:fruit'],
  raspberry: ['category:fruit'],
  coconut: ['category:fruit'],
  apricot: ['category:fruit'],
  fig: ['category:fruit'],
  date: ['category:fruit'],

  // category:tool
  square: ['category:tool'],
  stamp: ['category:tool'],
  float: ['category:tool'],
  hammer: ['category:tool'],
  wrench: ['category:tool'],
  shovel: ['category:tool'],
  screwdriver: ['category:tool'],
  saw: ['category:tool'],
  drill: ['category:tool'],
  pliers: ['category:tool'],
  chisel: ['category:tool'],
  axe: ['category:tool'],
  rake: ['category:tool'],
  scissors: ['category:tool'],
  mallet: ['category:tool'],
  jack: ['category:tool'],
  bit: ['category:tool'],
  pick: ['category:tool'],
  plane: ['category:tool', 'category:vehicle'],
  knife: ['category:tool'],
  file: ['category:tool'],
  punch: ['category:tool'],
  tap: ['category:tool'],
  blade: ['category:tool'],

  // category:vehicle
  rocket: ['category:vehicle'],
  car: ['category:vehicle'],
  bicycle: ['category:vehicle'],
  tractor: ['category:vehicle'],
  scooter: ['category:vehicle'],
  drone: ['category:vehicle'],
  spacecraft: ['category:vehicle'],
  truck: ['category:vehicle'],
  motorcycle: ['category:vehicle'],
  airplane: ['category:vehicle'],
  helicopter: ['category:vehicle'],
  boat: ['category:vehicle'],
  ship: ['category:vehicle'],
  van: ['category:vehicle'],
  submarine: ['category:vehicle'],
  sled: ['category:vehicle'],
  wagon: ['category:vehicle'],
  coach: ['category:vehicle'],
  cab: ['category:vehicle'],
  bike: ['category:vehicle'],
  tank: ['category:vehicle'],
  chopper: ['category:vehicle'],
  trailer: ['category:vehicle'],
  aircraft: ['category:vehicle'],
  cart: ['category:vehicle'],
  rig: ['category:vehicle'],
  yacht: ['category:vehicle'],

  // category:body-part
  brain: ['category:body-part'],
  face: ['category:body-part'],
  elbow: ['category:body-part'],
  ankle: ['category:body-part'],
  wrist: ['category:body-part'],
  thumb: ['category:body-part'],
  shoulder: ['category:body-part'],
  eye: ['category:body-part'],
  bone: ['category:body-part'],
  backbone: ['category:body-part'],
  leg: ['category:body-part'],
  hand: ['category:body-part'],
  finger: ['category:body-part'],
  knee: ['category:body-part'],
  spine: ['category:body-part'],
  rib: ['category:body-part'],
  lung: ['category:body-part'],
  heart: ['category:body-part'],
  stomach: ['category:body-part'],
  neck: ['category:body-part'],
  chest: ['category:body-part'],
  back: ['category:body-part'],
  head: ['category:body-part'],
  hair: ['category:body-part'],
  mouth: ['category:body-part'],
  nose: ['category:body-part'],
  arm: ['category:body-part'],
  foot: ['category:body-part'],
  skin: ['category:body-part'],
  throat: ['category:body-part'],
  tongue: ['category:body-part'],
  flesh: ['category:body-part'],
  nail: ['category:body-part'],
  belly: ['category:body-part'],
  hip: ['category:body-part'],
  liver: ['category:body-part'],
  muscle: ['category:body-part'],
  tooth: ['category:body-part'],
  gum: ['category:body-part'],
  palm: ['category:body-part'],
  chin: ['category:body-part'],
  toe: ['category:body-part'],
  lip: ['category:body-part'],
  gut: ['category:body-part'],
  kidney: ['category:body-part'],
  breast: ['category:body-part'],

  // property:kitchen
  dinner: ['property:kitchen'],
  food: ['property:kitchen'],
  tea: ['property:kitchen'],
  cook: ['property:kitchen'],
  cooking: ['property:kitchen'],
  sink: ['property:kitchen'],
  chef: ['property:kitchen'],
  dining: ['property:kitchen'],
  cooked: ['property:kitchen'],
  oven: ['property:kitchen'],
  refrigerator: ['property:kitchen'],
}
