import { HIDDEN_WORD_GROUPS } from '../words/fixedLists'
import type { PartOfSpeech } from '../words/types'
import { RULE_PARAMS } from './ruleParams'
import type { Rule } from './types'

// Rules built from a parameter list rather than hand-written one at a time.
// This is what takes the taxonomy from ~19 usable rules (a repeat every two
// weeks on the medium tier) to a few hundred.
//
// The parameters live in ruleParams.ts, which is GENERATED by
// `npm run content:build-rule-params` after counting real coverage against the
// word bank. That indirection matters: the old hand-maintained letter list
// excluded j/x/z based on counts taken against a 417-word bank and nobody
// re-ran them after it grew to 5,000 (the real numbers were j:96, x:78, z:41),
// so three rules sat unusable for months. Regenerating the params after a
// word-bank change now unlocks newly-viable rules automatically.

function article(word: string): string {
  return /^[aeiou]/.test(word) ? 'an' : 'a'
}

/** "The word hides ANIMAL inside it" — one rule per target. */
export function hiddenWordRule(target: string): Rule {
  return {
    id: `hidden-word-${target}`,
    name: `Hidden "${target}"`,
    templateId: 'hidden-word',
    descriptionTemplate: `The word hides "${target}" inside it.`,
    family: 'lexical-structural',
    subtlety: 4,
    aha: 4,
    evaluate: (word) => word.features.hiddenWordHits.includes(target),
  }
}

/**
 * "The word hides a body part inside it" — the group version, which is a
 * better puzzle than any single target: the player gets a category insight
 * rather than spotting one fixed string.
 */
export function hiddenGroupRule(group: keyof typeof HIDDEN_WORD_GROUPS): Rule {
  const members = new Set<string>(HIDDEN_WORD_GROUPS[group])
  return {
    id: `hidden-group-${group.replace(/\s+/g, '-')}`,
    name: `Hides ${article(group)} ${group}`,
    templateId: 'hidden-group',
    descriptionTemplate: `The word hides the name of ${article(group)} ${group} inside it.`,
    family: 'lexical-structural',
    subtlety: 5,
    aha: 5,
    evaluate: (word) => word.features.hiddenWordHits.some((hit) => members.has(hit)),
    variantOf: (word) => word.features.hiddenWordHits.find((hit) => members.has(hit)) ?? null,
  }
}

export function startsWithRule(prefix: string): Rule {
  return {
    id: `starts-with-${prefix}`,
    name: `Starts With "${prefix.toUpperCase()}"`,
    templateId: 'starts-with',
    descriptionTemplate: `The word starts with "${prefix.toUpperCase()}".`,
    family: 'lexical-structural',
    subtlety: prefix.length > 1 ? 3 : 2,
    aha: 2,
    evaluate: (word) => word.spelling.startsWith(prefix),
  }
}

export function endsWithRule(suffix: string): Rule {
  return {
    id: `ends-with-${suffix}`,
    name: `Ends With "${suffix.toUpperCase()}"`,
    templateId: 'ends-with',
    descriptionTemplate: `The word ends with "${suffix.toUpperCase()}".`,
    family: 'lexical-structural',
    subtlety: suffix.length > 1 ? 3 : 2,
    aha: 3,
    evaluate: (word) => word.spelling.endsWith(suffix),
  }
}

export function wordLengthRule(length: number): Rule {
  return {
    id: `word-length-${length}`,
    name: `Exactly ${length} Letters`,
    templateId: 'word-length',
    descriptionTemplate: `The word is exactly ${length} letters long.`,
    family: 'lexical-structural',
    subtlety: 2,
    // Counting letters is mechanical, not an insight — kept as rare filler.
    aha: 1,
    evaluate: (word) => word.length === length,
  }
}

const POS_LABEL: Record<string, string> = {
  noun: 'a noun',
  verb: 'a verb',
  adjective: 'an adjective',
  adverb: 'an adverb',
}

export function partOfSpeechRule(pos: PartOfSpeech): Rule {
  return {
    id: `part-of-speech-${pos}`,
    name: `Is ${POS_LABEL[pos] ?? pos}`,
    templateId: 'part-of-speech',
    descriptionTemplate: `The word is ${POS_LABEL[pos] ?? pos}.`,
    family: 'semantic-knowledge',
    subtlety: 3,
    aha: 3,
    evaluate: (word) => word.partOfSpeech === pos,
  }
}

export const GENERATED_RULES: Rule[] = [
  ...RULE_PARAMS.hiddenWords.map(hiddenWordRule),
  ...RULE_PARAMS.hiddenGroups.map((g) => hiddenGroupRule(g as keyof typeof HIDDEN_WORD_GROUPS)),
  ...RULE_PARAMS.startsWith.map(startsWithRule),
  ...RULE_PARAMS.endsWith.map(endsWithRule),
  ...RULE_PARAMS.wordLengths.map(wordLengthRule),
  ...RULE_PARAMS.partsOfSpeech.map((p) => partOfSpeechRule(p as PartOfSpeech)),
]
