import { CATEGORY_DEFINITIONS, categoryTag } from '../words/categories.js'
import { HIDDEN_WORD_GROUPS } from '../words/fixedLists.js'
import { RULE_PARAMS } from './ruleParams.js'
import type { Rule } from './types.js'

// Rules built from a parameter list rather than hand-written one at a time.
// This is what takes the taxonomy from ~19 usable rules (a repeat every two
// weeks on the medium tier) to a few hundred.
//
// The parameters live in ruleParams.ts, which is GENERATED by
// `npm run content:build-rule-params` after counting real coverage against the
// word bank. That indirection matters: the old hand-maintained letter list
// excluded j/x/z based on counts taken against a 417-word bank and nobody
// re-ran them after it grew to 5,000 (the real numbers were j:96, x:78, z:41),
// so three rules sat unusable for months. Regenerating the params after a
// word-bank change now unlocks newly-viable rules automatically.

/**
 * ARPAbet symbols a player would not recognise, in the reveal's own vocabulary.
 * Only the phonemes that can survive buildRuleParams' spelling-variety gate need
 * an entry; anything else falls through to the symbol itself.
 */
const SOUND_LABEL: Record<string, string> = { JH: 'J', ZH: 'ZH', HH: 'H' }

function article(word: string): string {
  return /^[aeiou]/.test(word) ? 'an' : 'a'
}

/** "The word hides ANIMAL inside it" — one rule per target. */
export function hiddenWordRule(target: string): Rule {
  return {
    id: `hidden-word-${target}`,
    name: `Hidden "${target}"`,
    templateId: 'hidden-word',
    descriptionTemplate: `The word hides "${target}" inside it.`,
    family: 'lexical-structural',
    mechanic: 'word-inside',
    // Was 4, which made every hidden-word rule spicy-only — one day a week.
    // It is the best-performing template in the whole taxonomy: 25% of its
    // puzzles get rejected, against 80% for ends-with and 88% for starts-with.
    // Locking the good material to Saturdays while filler carried the weekdays
    // was backwards. 3 keeps it spicy-eligible and adds it to medium.
    subtlety: 3,
    aha: 4,
    evaluate: (word) => word.features.hiddenWordHits.includes(target),
  }
}

/**
 * "The word hides a body part inside it" — the group version, which is a
 * better puzzle than any single target: the player gets a category insight
 * rather than spotting one fixed string.
 */
export function hiddenGroupRule(group: keyof typeof HIDDEN_WORD_GROUPS): Rule {
  const members = new Set<string>(HIDDEN_WORD_GROUPS[group])
  return {
    id: `hidden-group-${group.replace(/\s+/g, '-')}`,
    name: `Hides ${article(group)} ${group}`,
    templateId: 'hidden-group',
    descriptionTemplate: `The word hides the name of ${article(group)} ${group} inside it.`,
    family: 'lexical-structural',
    mechanic: 'word-inside',
    // Was 5, which made the highest-rated template in the taxonomy spicy-only —
    // one day a week for the puzzles most worth playing. The same mistake
    // hidden-word was in before the audit, and less defensible here: spotting
    // *some* animal is easier than spotting one specific target, so the group
    // version was rated harder than the individual version it generalises.
    // 3 keeps it spicy-eligible and adds it to medium.
    subtlety: 3,
    aha: 5,
    evaluate: (word) => word.features.hiddenWordHits.some((hit) => members.has(hit)),
    variantOf: (word) => word.features.hiddenWordHits.find((hit) => members.has(hit)) ?? null,
  }
}

export function startsWithRule(prefix: string): Rule {
  return {
    id: `starts-with-${prefix}`,
    name: `Starts With "${prefix.toUpperCase()}"`,
    templateId: 'starts-with',
    descriptionTemplate: `The word starts with "${prefix.toUpperCase()}".`,
    family: 'lexical-structural',
    mechanic: 'letter-pattern',
    subtlety: prefix.length > 1 ? 3 : 2,
    // 88% of starts-with puzzles have been rejected — the worst rate of any
    // template. aha is a selection weight (pickTrueRule uses aha / (1 +
    // rejectCount)), so rating it as filler is what stops it filling the
    // review queue with puzzles nobody wants.
    aha: 1,
    evaluate: (word) => word.spelling.startsWith(prefix),
  }
}

export function endsWithRule(suffix: string): Rule {
  return {
    id: `ends-with-${suffix}`,
    name: `Ends With "${suffix.toUpperCase()}"`,
    templateId: 'ends-with',
    descriptionTemplate: `The word ends with "${suffix.toUpperCase()}".`,
    family: 'lexical-structural',
    mechanic: 'letter-pattern',
    subtlety: suffix.length > 1 ? 3 : 2,
    // 80% rejected, yet rated neutral — the rating disagreed with every review
    // decision ever made about it. Same reasoning as startsWithRule.
    aha: 1,
    evaluate: (word) => word.spelling.endsWith(suffix),
  }
}

export function wordLengthRule(length: number): Rule {
  return {
    id: `word-length-${length}`,
    name: `Exactly ${length} Letters`,
    templateId: 'word-length',
    descriptionTemplate: `The word is exactly ${length} letters long.`,
    family: 'lexical-structural',
    mechanic: 'letter-pattern',
    subtlety: 2,
    // Counting letters is mechanical, not an insight — kept as rare filler.
    aha: 1,
    evaluate: (word) => word.length === length,
  }
}

const CATEGORY_BY_ID = new Map(CATEGORY_DEFINITIONS.map((c) => [c.id, c]))

/**
 * "The word names a bird" — semantic category membership, the family with the
 * most headroom now that tags come from the AI tagger rather than 227
 * hand-reviewed words. Rule ids match the previously hand-written ones
 * (`category-animal` etc.) so puzzles already approved against them still
 * resolve.
 */
export function categoryRule(id: string): Rule {
  const def = CATEGORY_BY_ID.get(id)
  if (!def) throw new Error(`Unknown category id: ${id}`)
  const tag = categoryTag(id)
  return {
    id: `category-${id}`,
    name: `Is ${def.label}`,
    templateId: 'category',
    descriptionTemplate: `The word names ${def.label}.`,
    family: 'semantic-knowledge',
    mechanic: 'meaning',
    subtlety: def.subtlety,
    // Recognising a shared category is a genuine insight rather than a
    // letter-counting exercise, so these sit high on the aha axis.
    aha: 4,
    evaluate: (word) => word.tags.includes(tag),
  }
}

export const GENERATED_RULES: Rule[] = [
  ...RULE_PARAMS.categories.map(categoryRule),
  ...RULE_PARAMS.hiddenWords.map(hiddenWordRule),
  ...RULE_PARAMS.hiddenGroups.map((g) => hiddenGroupRule(g as keyof typeof HIDDEN_WORD_GROUPS)),
  ...RULE_PARAMS.startsWith.map(startsWithRule),
  ...RULE_PARAMS.endsWith.map(endsWithRule),
  ...RULE_PARAMS.wordLengths.map(wordLengthRule),
  ...RULE_PARAMS.syllableCounts.map(syllableCountRule),
  ...RULE_PARAMS.rhymes.map(rhymeRule),
  ...RULE_PARAMS.initialSounds.map(initialSoundRule),
  silentLettersRule(RULE_PARAMS.silentThreshold),
  homophoneRule(),
  silentFirstLetterRule(),
  longOneSyllableRule(6),
]

// --- sound rules -------------------------------------------------------------
//
// A third axis. Every other rule in the taxonomy asks about spelling or about
// meaning; these ask what the word sounds like, which a player has to reach for
// differently — often by saying the word under their breath.
//
// All of them read `word.phonetics`, precomputed from CMUdict into
// words/phonetics.ts. It is null for the ~2% of the bank with no pronunciation,
// and every rule below treats that as OUT. Never as a match: a word the game
// cannot pronounce silently becoming an IN answer is a wrong answer the player
// has no way to reason about.

/** "Three syllables when you say it out loud." */
export function syllableCountRule(count: number): Rule {
  return {
    id: `syllables-${count}`,
    name: `${count} Syllable${count === 1 ? '' : 's'}`,
    templateId: 'syllable-count',
    descriptionTemplate: `The word has exactly ${count} syllable${count === 1 ? '' : 's'} when spoken.`,
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    // Counting, like word-length — but counting something you can only get at
    // by pronouncing the word, which is a different act from counting letters.
    aha: 3,
    evaluate: (word) => word.phonetics?.syllables === count,
  }
}

/**
 * "Longer written than spoken." The player has to notice the gap between how a
 * word looks and how it sounds.
 *
 * Named for what it actually measures. The count is letters minus phonemes, so
 * digraphs land in it too — "cheese" scores 3 without having three silent
 * letters in the way anyone means that phrase. Calling it "Silent Letters"
 * would promise something the evaluator doesn't deliver, and the reveal text is
 * the one thing a player checks their reasoning against.
 */
export function silentLettersRule(minSilent: number): Rule {
  return {
    id: `silent-letters-${minSilent}`,
    name: 'More Letters Than Sounds',
    templateId: 'silent-letters',
    descriptionTemplate: `The word has at least ${minSilent} more letters than it has sounds.`,
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 4,
    evaluate: (word) => (word.phonetics?.silent ?? 0) >= minSilent,
  }
}

/** "Sounds exactly like another word" — great/grate, throne/thrown, pear/pair. */
export function homophoneRule(): Rule {
  return {
    id: 'has-homophone',
    name: 'Sounds Like Another Word',
    templateId: 'homophone',
    descriptionTemplate: 'The word sounds exactly like a different word.',
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 4,
    evaluate: (word) => word.phonetics?.homophone === true,
  }
}

/**
 * "They all start with a K sound" — coffee, kitten, quiet, chemistry.
 *
 * The sharpest thing the sound family can do, and the one rule here that no
 * spelling rule could imitate: the words share a sound and share no letter. Only
 * phonemes spelled several ways in the bank get a rule at all
 * (MIN_MINORITY_SPELLING_SHARE), because "starts with a B sound" is just "starts
 * with B" with extra steps.
 *
 * `variantOf` returns the first *letter*, which matters more here than anywhere
 * else in the taxonomy: it makes draftClueSet span at least two spellings, so the
 * clue set is coffee/kitten/quiet rather than three c-words that teach the player
 * the wrong rule.
 */
export function initialSoundRule(phoneme: string): Rule {
  const label = SOUND_LABEL[phoneme] ?? phoneme
  return {
    id: `initial-sound-${phoneme.toLowerCase()}`,
    name: `Starts With a "${label}" Sound`,
    templateId: 'initial-sound',
    descriptionTemplate: `The word starts with a "${label}" sound, however it is spelled.`,
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 5,
    evaluate: (word) => word.phonetics?.first === phoneme,
    variantOf: (word) => (word.phonetics?.first === phoneme ? word.spelling[0] : null),
  }
}

/**
 * "The first letter makes no sound at all" — knee, gnome, wrist, write, hour.
 *
 * 91 words, from a closed list of silent initial digraphs plus silent H; see
 * SILENT_INITIALS in scripts/buildPhonetics.ts for why that list is hardcoded
 * rather than inferred.
 *
 * `variantOf` is the silent letter. Without it the first real batch drew
 * `wrestling, knowing, wrong` — a clue set whose shared -ng ending generated
 * three spurious decoys ("Ends With NG", "Contains G") and taught the player to
 * look at the end of the word rather than the start. Spanning variants gives
 * knee / wrist / honest instead.
 */
export function silentFirstLetterRule(): Rule {
  return {
    id: 'silent-first-letter',
    name: 'Silent First Letter',
    templateId: 'silent-first-letter',
    descriptionTemplate: 'The word begins with a letter you do not pronounce.',
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 5,
    evaluate: (word) => word.phonetics?.silentFirst === true,
    variantOf: (word) => (word.phonetics?.silentFirst ? word.spelling[0] : null),
  }
}

/**
 * "A long word you say in one beat" — cheese, mosque, square, spring, wrench.
 *
 * Spelling against sound again, from the other direction: the word looks like it
 * should take a while and doesn't. `minLength` is 6 rather than swept, because
 * the three candidate lengths are the same idea at three strengths and only one
 * should ship; soundRules.test.ts asserts the coverage floor so a bank change
 * that starved it would fail loudly.
 */
export function longOneSyllableRule(minLength: number): Rule {
  return {
    id: `one-syllable-long-${minLength}`,
    name: 'Long, But One Syllable',
    templateId: 'one-syllable-long',
    descriptionTemplate: `The word is ${minLength} letters or more, but only one syllable when spoken.`,
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 5,
    evaluate: (word) => word.phonetics?.syllables === 1 && word.length >= minLength,
  }
}

/**
 * "They all rhyme." The rhyme key is the last stressed vowel sound onward, so
 * it groups by how words END in speech rather than in spelling — "eight"
 * rhymes with "late" here, which no ends-with rule can express.
 *
 * `anchor` is a common bank word carrying the same key, and it exists purely so
 * the reveal names something. All 73 rhyme rules used to end with the identical
 * sentence, "The words all rhyme with each other" — 73 rules that read as one
 * puzzle played 73 ways, which is more repetitive than the hidden-word family
 * it was quietly out-drawing. "They all rhyme with RAIN" tells the player what
 * they were listening for.
 */
export function rhymeRule([key, anchor]: readonly [string, string]): Rule {
  return {
    id: `rhyme-${key.toLowerCase()}`,
    name: `Rhymes With "${anchor.toUpperCase()}"`,
    templateId: 'rhyme',
    descriptionTemplate: `The words all rhyme with "${anchor}".`,
    family: 'lexical-structural',
    mechanic: 'sound',
    subtlety: 3,
    aha: 3,
    evaluate: (word) => word.phonetics?.rhyme === key,
  }
}
