// AUTO-GENERATED by content-engine/scripts/buildRuleParams.ts — do not hand-edit.
// Every parameter here cleared a real coverage check against the word bank;
// re-run `npm run content:build-rule-params` after changing the bank.

export const RULE_PARAMS = {
  hiddenWords: ["one","ten","ear","arm","leg","hip","rib","lip","shin","chin","back","hand","head","cat","rat","ant","owl","hen","ape","bat","ram","eel","red","tan","ash","pea","oat","ham","tea","ale","cap","ice","rain","table","car","van","ship"],
  hiddenGroups: ["number","body part","animal","color","food","drink","piece of clothing","kind of weather","piece of furniture","vehicle"],
  startsWith: ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","y","z","ch","sh","th","wh","st","pr","tr","br","cl","fl"],
  endsWith: ["a","b","c","d","e","f","g","h","i","k","l","m","n","o","p","r","s","t","u","w","x","y","ed","er","ly","ng","ion","ing","est","ous","ful","ent","ance","ment","ness","able","tion","less"],
  wordLengths: [3,4,5,6,7,8,9,10],
  categories: ["animal","bird","fish","insect","plant","tree","flower","body-part","food","fruit","vegetable","drink","clothing","furniture","tool","weapon","vehicle","container","instrument","toy","building","room","landform","celestial","profession","relative","emotion","weather","color","metal","sport","illness","time-period"],
  syllableCounts: [1,3,4,5],
  silentThreshold: 3,
  rhymes: [["AAK","rock"],["AAN","don"],["AAP","stop"],["AAR","far"],["AARD","hard"],["AARK","dark"],["AAT","not"],["AEK","back"],["AEKT","fact"],["AEM","program"],["AEN","man"],["AEND","understand"],["AET","fat"],["AOL","call"],["AOR","door"],["AORD","lord"],["AWND","around"],["AWS","house"],["AWT","doubt"],["AY","guy"],["AYD","inside"],["AYER","fire"],["AYM","time"],["AYN","fine"],["AYND","find"],["AYT","right"],["AYZ","eyes"],["AYZD","surprised"],["EHD","dead"],["EHKT","perfect"],["EHL","tell"],["EHND","friend"],["EHNT","president"],["EHR","care"],["EHRIY","marry"],["EHS","yes"],["EHST","best"],["EHT","let"],["EY","say"],["EYD","made"],["EYK","break"],["EYL","jail"],["EYN","explain"],["EYS","case"],["EYSHAHN","information"],["EYT","wait"],["EYTER","later"],["EYTIHD","related"],["EYTIHNG","waiting"],["IHK","pick"],["IHL","will"],["IHN","win"],["IHNG","thing"],["IHP","trip"],["IHR","year"],["IHSHAHN","position"],["IHT","sit"],["IY","three"],["IYD","need"],["IYK","week"],["IYL","feel"],["IYN","mean"],["IYT","meet"],["IYZ","please"],["OW","know"],["OWL","whole"],["OWN","known"],["OWT","note"],["UW","new"],["UWD","food"],["UWM","room"],["UWN","soon"],["UWT","shoot"]],
} as const
