// Generates content-engine/words/phonetics.ts from the CMU Pronouncing
// Dictionary — the build-time half of the sound rules.
//
// Why a generated file rather than a lookup: `RULES` is imported by the Netlify
// functions, so a rule calling into CMUdict's 135,000 entries would pull the
// whole dictionary into every function bundle. This bakes the four facts the
// rules actually need into ~15,000 small records, and `cmu-pronouncing-
// dictionary` stays a devDependency that never ships — exactly how WordNet and
// SUBTLEXus are already used.
//
// Re-run after any word-bank change: npm run content:build-phonetics

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { dictionary } from 'cmu-pronouncing-dictionary'
import { BULK_SEED_WORDS } from '../words/bulkSeedWords.js'
import { SEED_WORDS } from '../words/seedWords.js'

// ARPAbet vowels carry a stress digit; consonants never do. Both facts are used
// below — the digits count syllables, and the vowel set finds the rhyme.
const VOWEL = /^(AA|AE|AH|AO|AW|AY|EH|ER|EY|IH|IY|OW|OY|UH|UW)$/

interface Entry {
  syllables: number
  rhyme: string | null
  silent: number
  homophone: boolean
}

function main(): void {
  const dict = dictionary as Record<string, string>
  const spellings = [...SEED_WORDS, ...BULK_SEED_WORDS].map((w) => w.spelling)

  const entries = new Map<string, Entry>()
  const byPronunciation = new Map<string, string[]>()
  let missing = 0

  for (const spelling of spellings) {
    const raw = dict[spelling]
    if (!raw) {
      missing++
      continue
    }
    const phonemes = raw.replace(/\d/g, '').trim().split(/\s+/)
    const syllables = (raw.match(/\d/g) ?? []).length

    // A rhyme runs from the last STRESSED vowel, not merely the last vowel.
    // That distinction is the whole quality of the rule: the last-vowel reading
    // grouped "surface", "tennis" and "bus" on a shared unstressed schwa —
    // technically a rhyme, but nobody hears it — while the stressed reading
    // gives dark/park/shark and smile/file/style, which people do.
    // CMUdict marks stress on every vowel: 1 primary, 2 secondary, 0 none.
    const withStress = raw.trim().split(/\s+/)
    let rhyme: string | null = null
    for (let i = withStress.length - 1; i >= 0; i--) {
      if (/[12]$/.test(withStress[i])) {
        rhyme = phonemes.slice(i).join('')
        break
      }
    }
    // No stressed vowel at all (rare) still deserves a key — fall back to the
    // last vowel of any kind rather than dropping the word from every rhyme.
    if (rhyme === null) {
      for (let i = phonemes.length - 1; i >= 0; i--) {
        if (VOWEL.test(phonemes[i])) {
          rhyme = phonemes.slice(i).join('')
          break
        }
      }
    }

    entries.set(spelling, {
      syllables,
      rhyme,
      silent: spelling.length - phonemes.length,
      homophone: false,
    })

    const key = phonemes.join(' ')
    if (!byPronunciation.has(key)) byPronunciation.set(key, [])
    byPronunciation.get(key)!.push(spelling)
  }

  // Homophones are a bank-wide property — resolved here, once, so no rule has
  // to scan the bank at evaluate() time.
  let homophoneWords = 0
  for (const group of byPronunciation.values()) {
    if (group.length < 2) continue
    for (const spelling of group) {
      entries.get(spelling)!.homophone = true
      homophoneWords++
    }
  }

  // The rhyme key joins phonemes with no separator, so two different phoneme
  // sequences must never produce the same string. ARPAbet's fixed 39-symbol
  // set makes that safe in theory; this asserts it rather than assuming, since
  // a silent collision would merge two unrelated rhymes into one wrong rule.
  const rhymeSources = new Map<string, Set<string>>()
  for (const [spelling, e] of entries) {
    if (!e.rhyme) continue
    const withStress = dict[spelling].trim().split(/\s+/)
    const bare = withStress.map((ph) => ph.replace(/\d/g, ''))
    let start = -1
    for (let i = withStress.length - 1; i >= 0; i--) {
      if (/[12]$/.test(withStress[i])) {
        start = i
        break
      }
    }
    if (start === -1) {
      for (let i = bare.length - 1; i >= 0; i--) {
        if (VOWEL.test(bare[i])) {
          start = i
          break
        }
      }
    }
    if (start === -1) continue
    if (!rhymeSources.has(e.rhyme)) rhymeSources.set(e.rhyme, new Set())
    rhymeSources.get(e.rhyme)!.add(bare.slice(start).join(' '))
  }
  const collisions = [...rhymeSources].filter(([, set]) => set.size > 1)
  if (collisions.length > 0) {
    console.error(`FATAL: ${collisions.length} rhyme key(s) map to more than one phoneme sequence.`)
    for (const [key, set] of collisions.slice(0, 5))
      console.error(`  ${key} <- ${[...set].join(' | ')}`)
    process.exit(1)
  }

  const lines = [
    '// AUTO-GENERATED by content-engine/scripts/buildPhonetics.ts — do not hand-edit.',
    '// Source: the CMU Pronouncing Dictionary. Re-run `npm run content:build-phonetics`',
    '// after changing the word bank.',
    '//',
    `// ${entries.size} of ${spellings.length} words have a pronunciation (${missing} missing).`,
    '',
    "import type { Phonetics } from './types.js'",
    '',
    'export const PHONETICS: Record<string, Phonetics> = {',
    ...[...entries]
      .sort(([a], [b]) => (a < b ? -1 : 1))
      .map(
        ([spelling, e]) =>
          `  ${JSON.stringify(spelling)}: { syllables: ${e.syllables}, rhyme: ${e.rhyme === null ? 'null' : JSON.stringify(e.rhyme)}, silent: ${e.silent}, homophone: ${e.homophone} },`
      ),
    '}',
    '',
  ]
  writeFileSync(join(process.cwd(), 'content-engine', 'words', 'phonetics.ts'), lines.join('\n'))

  const sylCounts = new Map<number, number>()
  for (const e of entries.values())
    sylCounts.set(e.syllables, (sylCounts.get(e.syllables) ?? 0) + 1)

  console.log(
    `Words with a pronunciation: ${entries.size}/${spellings.length} (${missing} missing)`
  )
  console.log(`  homophones: ${homophoneWords} words`)
  console.log(`  distinct rhymes: ${rhymeSources.size} (no key collisions)`)
  console.log(
    `  syllables: ${[...sylCounts]
      .sort((a, b) => a[0] - b[0])
      .map(([n, c]) => `${n}:${c}`)
      .join(' ')}`
  )
  console.log(`\nWrote content-engine/words/phonetics.ts`)
}

main()
