// Sweeps every candidate rule parameter, counts real coverage against the word
// bank, and writes the ones that clear the floor to rules/ruleParams.ts.
//
// Why generated rather than hand-maintained: the old `contains-letter` list
// excluded j/x/z citing coverage counts taken against a 417-word bank. Nobody
// re-ran them after the bank grew to 5,000 (j:96, x:78, z:41), so three usable
// rules sat dead for months. Re-running this after any word-bank change now
// promotes newly-viable parameters automatically and demotes ones that fell
// below the floor.
// Run with: npm run content:build-rule-params

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { HIDDEN_WORD_GROUPS, HIDDEN_WORD_TARGETS } from '../words/fixedLists'
import type { PartOfSpeech, Word } from '../words/types'
import { buildWordBank } from '../words/wordBank'

// A rule needs enough IN words to draft 3 clues plus pool guests without
// leaning on the same handful every time it's drawn.
const MIN_COVERAGE = 25
// Above this share of the bank a rule stops being a rule and becomes a
// background condition — it survives the clue stage on nearly every puzzle and
// permanently occupies a decoy slot (what `no-adjacent-vowels` did at 73%).
const MAX_COVERAGE_SHARE = 0.35

const ALPHABET = 'abcdefghijklmnopqrstuvwxyz'.split('')
// Multi-letter starts/ends worth trying. Suffixes carry more signal than
// prefixes (English marks grammar at the end), so the list leans that way.
const PREFIX_CANDIDATES = [...ALPHABET, 'ch', 'sh', 'th', 'wh', 'st', 'pr', 'tr', 'br', 'cl', 'fl']
const SUFFIX_CANDIDATES = [
  ...ALPHABET,
  'ed',
  'er',
  'ly',
  'ng',
  'ion',
  'ing',
  'est',
  'ous',
  'ful',
  'ent',
  'ance',
  'ment',
  'ness',
  'able',
  'tion',
  'less',
]
const PARTS_OF_SPEECH: PartOfSpeech[] = ['noun', 'verb', 'adjective', 'adverb']

interface Swept<T> {
  kept: T[]
  rejected: { param: T; count: number; reason: string }[]
}

function sweep<T>(candidates: readonly T[], bank: Word[], matches: (w: Word, p: T) => boolean): Swept<T> {
  const kept: T[] = []
  const rejected: { param: T; count: number; reason: string }[] = []
  for (const param of candidates) {
    const count = bank.filter((w) => matches(w, param)).length
    if (count < MIN_COVERAGE) rejected.push({ param, count, reason: 'too few' })
    else if (count / bank.length > MAX_COVERAGE_SHARE) rejected.push({ param, count, reason: 'too broad' })
    else kept.push(param)
  }
  return { kept, rejected }
}

function report<T>(label: string, swept: Swept<T>, total: number): void {
  const tooFew = swept.rejected.filter((r) => r.reason === 'too few').length
  const tooBroad = swept.rejected.filter((r) => r.reason === 'too broad').length
  console.log(`  ${label}: kept ${swept.kept.length}/${total} (${tooFew} too few, ${tooBroad} too broad)`)
}

function main(): void {
  // Blocked words can never be drafted, so counting them would overstate a
  // parameter's real coverage and promote rules the generator can't fill.
  const bank = buildWordBank().filter((w) => !w.safety.blocked)
  console.log(`Word bank: ${bank.length} words. Coverage floor ${MIN_COVERAGE}, ceiling ${MAX_COVERAGE_SHARE * 100}%.\n`)

  const hiddenWords = sweep(HIDDEN_WORD_TARGETS, bank, (w, t) => w.features.hiddenWordHits.includes(t))
  const groupNames = Object.keys(HIDDEN_WORD_GROUPS) as (keyof typeof HIDDEN_WORD_GROUPS)[]
  const hiddenGroups = sweep(groupNames, bank, (w, g) => {
    const members = new Set<string>(HIDDEN_WORD_GROUPS[g])
    return w.features.hiddenWordHits.some((hit) => members.has(hit))
  })
  const startsWith = sweep(PREFIX_CANDIDATES, bank, (w, p) => w.spelling.startsWith(p))
  const endsWith = sweep(SUFFIX_CANDIDATES, bank, (w, s) => w.spelling.endsWith(s))
  const wordLengths = sweep([3, 4, 5, 6, 7, 8, 9, 10], bank, (w, n) => w.length === n)
  const partsOfSpeech = sweep(PARTS_OF_SPEECH, bank, (w, p) => w.partOfSpeech === p)

  report('hidden-word', hiddenWords, HIDDEN_WORD_TARGETS.length)
  report('hidden-group', hiddenGroups, groupNames.length)
  report('starts-with', startsWith, PREFIX_CANDIDATES.length)
  report('ends-with', endsWith, SUFFIX_CANDIDATES.length)
  report('word-length', wordLengths, 8)
  report('part-of-speech', partsOfSpeech, PARTS_OF_SPEECH.length)

  const lines = [
    '// AUTO-GENERATED by content-engine/scripts/buildRuleParams.ts — do not hand-edit.',
    '// Every parameter here cleared a real coverage check against the word bank;',
    '// re-run `npm run content:build-rule-params` after changing the bank.',
    '',
    'export const RULE_PARAMS = {',
    `  hiddenWords: ${JSON.stringify(hiddenWords.kept)},`,
    `  hiddenGroups: ${JSON.stringify(hiddenGroups.kept)},`,
    `  startsWith: ${JSON.stringify(startsWith.kept)},`,
    `  endsWith: ${JSON.stringify(endsWith.kept)},`,
    `  wordLengths: ${JSON.stringify(wordLengths.kept)},`,
    `  partsOfSpeech: ${JSON.stringify(partsOfSpeech.kept)},`,
    '} as const',
    '',
  ]
  writeFileSync(join(process.cwd(), 'content-engine', 'rules', 'ruleParams.ts'), lines.join('\n'))

  const total =
    hiddenWords.kept.length +
    hiddenGroups.kept.length +
    startsWith.kept.length +
    endsWith.kept.length +
    wordLengths.kept.length +
    partsOfSpeech.kept.length
  console.log(`\nWrote ${total} generated rules to content-engine/rules/ruleParams.ts`)
}

main()
