// Phase 10.6: expand the word bank from ~417 hand-picked words to ~5,000,
// sourced from a real frequency corpus rather than more hand-picking.
// Source: subtlex-word-frequencies (SUBTLEXus, 74,286 words by usage count
// in American English subtitles) — chosen after `wordlist-js` was tried and
// rejected (its largest tier had only 2,556 words and missed basics like
// "spoon"). Writes a new file (`words/bulkSeedWords.ts`), never touches the
// existing hand-curated `seedWords.ts` — that file's words already carry
// human-reviewed category tags (Phase 10.5 §2) that must not be lost.
// Run with: npm run content:expand-word-bank

import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import { Filter } from 'bad-words'
// Not part of natural's public export map (see dictionarySources.ts's note
// on that package's dynamic CJS exports) but a plain, statically-analyzable
// named export at this specific path — imports cleanly on its own.
import { words as STOPWORDS } from 'natural/lib/natural/util/stopwords.js'
import { fetchWordnetProfile, type WordnetProfile } from '../words/dictionarySources'
import { SEED_WORDS } from '../words/seedWords'
import type { SeedWord } from '../words/types'

const require = createRequire(import.meta.url)
const subtlex = require('subtlex-word-frequencies') as { word: string; count: number }[]

const TARGET_TOTAL = 15000
const MIN_LENGTH = 3
const MAX_LENGTH = 12
const POS_LOOKUP_BATCH_SIZE = 50
// Words are dropped after the WordNet check, so more candidates have to be
// examined than are ultimately kept.
const OVERSELECT_FACTOR = 1.6

// Interjections and filler that WordNet does recognize but which make poor
// puzzle content — they read as noise rather than words. Everything else in
// the corpus junk category (apostrophe-split fragments like `didn`/`isn`) is
// removed by the WordNet-known check instead of being enumerated here.
const NON_PUZZLE_WORDS = new Set([
  'hmm',
  'huh',
  'heh',
  'hey',
  'yeah',
  'yep',
  'yup',
  'nope',
  'nah',
  'whoa',
  'wow',
  'oops',
  'ugh',
  'aha',
  'okay',
  'gonna',
  'gotta',
  'wanna',
  'gotcha',
  'lemme',
  'dunno',
  'mrs',
  'mmm',
  'ooh',
  'shh',
  'psst',
  'yea',
  'nay',
])

const profanityFilter = new Filter()
const stopwordSet = new Set<string>(STOPWORDS)

function selectCandidates(limit: number): { spelling: string; count: number }[] {
  const existing = new Set(SEED_WORDS.map((s) => s.spelling))
  const seen = new Set<string>()
  const candidates: { spelling: string; count: number }[] = []

  for (const entry of subtlex) {
    const spelling = entry.word.toLowerCase()
    if (!/^[a-z]+$/.test(spelling)) continue
    if (spelling.length < MIN_LENGTH || spelling.length > MAX_LENGTH) continue
    if (existing.has(spelling) || seen.has(spelling)) continue
    if (stopwordSet.has(spelling)) continue // articles, pronouns, prepositions — not useful puzzle content
    if (NON_PUZZLE_WORDS.has(spelling)) continue
    if (profanityFilter.isProfane(spelling)) continue
    seen.add(spelling)
    candidates.push({ spelling, count: entry.count })
  }

  candidates.sort((a, b) => b.count - a.count)
  return candidates.slice(0, limit)
}

/**
 * Rank-based, continuous. The previous version bucketed everything into three
 * values (0.9/0.6/0.3), which made `frequencyScore` too coarse to tune a clue
 * floor against and gave `pickWeighted` only three distinct weights. Kept on
 * the same 0..1 scale and the same rough distribution so the existing 0.6
 * clue floor still means "roughly the commonest 40%". Floored above zero
 * because pickWeighted assumes positive weights.
 */
function frequencyScoreFor(rank: number, total: number): number {
  return Math.max(0.1, Number((1 - rank / total).toFixed(3)))
}

async function lookupProfiles(spellings: string[]): Promise<WordnetProfile[]> {
  const results: WordnetProfile[] = []
  for (let i = 0; i < spellings.length; i += POS_LOOKUP_BATCH_SIZE) {
    const batch = spellings.slice(i, i + POS_LOOKUP_BATCH_SIZE)
    results.push(...(await Promise.all(batch.map((s) => fetchWordnetProfile(s)))))
    if ((i / POS_LOOKUP_BATCH_SIZE) % 20 === 0) {
      console.log(
        `  checked ${Math.min(i + POS_LOOKUP_BATCH_SIZE, spellings.length)}/${spellings.length}...`
      )
    }
  }
  return results
}

function writeOutput(words: SeedWord[]): void {
  const lines = [
    '// AUTO-GENERATED by content-engine/scripts/expandWordBank.ts — do not hand-edit.',
    '// Sourced from subtlex-word-frequencies, filtered to words WordNet knows.',
    '// No `tags` yet — run content:tag-words + human review to populate them,',
    '// same rhythm as the hand-curated words in seedWords.ts.',
    "import type { SeedWord } from './types'",
    '',
    'export const BULK_SEED_WORDS: SeedWord[] = [',
    ...words.map(
      (w) =>
        `  { spelling: ${JSON.stringify(w.spelling)}, frequencyScore: ${w.frequencyScore}, partOfSpeech: ${JSON.stringify(w.partOfSpeech)}${w.properNoun ? ', properNoun: true' : ''} },`
    ),
    ']',
    '',
  ]
  writeFileSync(
    join(process.cwd(), 'content-engine', 'words', 'bulkSeedWords.ts'),
    lines.join('\n')
  )
}

async function main() {
  const wanted = TARGET_TOTAL - SEED_WORDS.length
  console.log(`Existing word bank: ${SEED_WORDS.length}. Target total: ${TARGET_TOTAL}.`)

  const candidates = selectCandidates(Math.ceil(wanted * OVERSELECT_FACTOR))
  console.log(`Examining ${candidates.length} candidates from ${subtlex.length} source words.`)

  console.log('Checking WordNet for existence, part of speech and proper-noun status...')
  const profiles = await lookupProfiles(candidates.map((c) => c.spelling))

  const known = candidates
    .map((c, i) => ({ ...c, profile: profiles[i] }))
    .filter((c) => c.profile.known)
  const dropped = candidates.length - known.length
  console.log(`Dropped ${dropped} candidates WordNet doesn't recognize (corpus fragments).`)

  const kept = known.slice(0, wanted)
  const words: SeedWord[] = kept.map((c, i) => ({
    spelling: c.spelling,
    frequencyScore: frequencyScoreFor(i, kept.length),
    partOfSpeech: c.profile.partOfSpeech,
    ...(c.profile.properNoun ? { properNoun: true } : {}),
  }))

  writeOutput(words)

  const posCounts = new Map<string, number>()
  for (const w of words) posCounts.set(w.partOfSpeech, (posCounts.get(w.partOfSpeech) ?? 0) + 1)
  console.log('\nPart-of-speech breakdown:', Object.fromEntries(posCounts))
  console.log(`Proper nouns flagged: ${words.filter((w) => w.properNoun).length}`)
  console.log(`\nWrote ${words.length} words to content-engine/words/bulkSeedWords.ts`)
  console.log(`New total word bank size: ${SEED_WORDS.length + words.length}`)
}

main().catch((err) => {
  console.error('expandWordBank failed:', err)
  process.exit(1)
})
