// Phase 10.6: expand the word bank from ~417 hand-picked words to ~5,000,
// sourced from a real frequency corpus rather than more hand-picking.
// Source: subtlex-word-frequencies (SUBTLEXus, 74,286 words by usage count
// in American English subtitles) — chosen after `wordlist-js` was tried and
// rejected (its largest tier had only 2,556 words and missed basics like
// "spoon"). Writes a new file (`words/bulkSeedWords.ts`), never touches the
// existing hand-curated `seedWords.ts` — that file's words already carry
// human-reviewed category tags (Phase 10.5 §2) that must not be lost.
// Run with: npm run content:expand-word-bank

import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import { Filter } from 'bad-words'
// Not part of natural's public export map (see dictionarySources.ts's note
// on that package's dynamic CJS exports) but a plain, statically-analyzable
// named export at this specific path — imports cleanly on its own.
import { words as STOPWORDS } from 'natural/lib/natural/util/stopwords.js'
import { fetchWordnetPartOfSpeech } from '../words/dictionarySources'
import { SEED_WORDS } from '../words/seedWords'
import type { PartOfSpeech, SeedWord } from '../words/types'

const require = createRequire(import.meta.url)
const subtlex = require('subtlex-word-frequencies') as { word: string; count: number }[]

const TARGET_TOTAL = 5000
const MIN_LENGTH = 3
const MAX_LENGTH = 12
const POS_LOOKUP_BATCH_SIZE = 25

const profanityFilter = new Filter()
const stopwordSet = new Set<string>(STOPWORDS)

function selectCandidates(): { spelling: string; count: number }[] {
  const existing = new Set(SEED_WORDS.map((s) => s.spelling))
  const seen = new Set<string>()
  const candidates: { spelling: string; count: number }[] = []

  for (const entry of subtlex) {
    const spelling = entry.word.toLowerCase()
    if (!/^[a-z]+$/.test(spelling)) continue
    if (spelling.length < MIN_LENGTH || spelling.length > MAX_LENGTH) continue
    if (existing.has(spelling) || seen.has(spelling)) continue
    if (stopwordSet.has(spelling)) continue // articles, pronouns, prepositions — not useful puzzle content
    if (profanityFilter.isProfane(spelling)) continue
    seen.add(spelling)
    candidates.push({ spelling, count: entry.count })
  }

  candidates.sort((a, b) => b.count - a.count)
  return candidates.slice(0, TARGET_TOTAL - SEED_WORDS.length)
}

function frequencyScoreFor(rank: number, total: number): number {
  const fraction = rank / total
  if (fraction < 1 / 3) return 0.9
  if (fraction < 2 / 3) return 0.6
  return 0.3
}

async function lookupPartsOfSpeech(spellings: string[]): Promise<PartOfSpeech[]> {
  const results: PartOfSpeech[] = []
  for (let i = 0; i < spellings.length; i += POS_LOOKUP_BATCH_SIZE) {
    const batch = spellings.slice(i, i + POS_LOOKUP_BATCH_SIZE)
    const tagged = await Promise.all(batch.map((s) => fetchWordnetPartOfSpeech(s)))
    results.push(...tagged)
    if ((i / POS_LOOKUP_BATCH_SIZE) % 20 === 0) {
      console.log(
        `  tagged ${Math.min(i + POS_LOOKUP_BATCH_SIZE, spellings.length)}/${spellings.length}...`
      )
    }
  }
  return results
}

function writeOutput(words: SeedWord[]): void {
  const lines = [
    '// AUTO-GENERATED by content-engine/scripts/expandWordBank.ts — do not hand-edit.',
    '// Sourced from subtlex-word-frequencies; re-run the script to regenerate.',
    '// No `tags` yet — run content:tag-words + human review to populate them,',
    '// same rhythm as the hand-curated words in seedWords.ts.',
    "import type { SeedWord } from './types'",
    '',
    'export const BULK_SEED_WORDS: SeedWord[] = [',
    ...words.map(
      (w) =>
        `  { spelling: ${JSON.stringify(w.spelling)}, frequencyScore: ${w.frequencyScore}, partOfSpeech: ${JSON.stringify(w.partOfSpeech)} },`
    ),
    ']',
    '',
  ]
  writeFileSync(
    join(process.cwd(), 'content-engine', 'words', 'bulkSeedWords.ts'),
    lines.join('\n')
  )
}

async function main() {
  console.log(`Existing word bank: ${SEED_WORDS.length}. Target total: ${TARGET_TOTAL}.`)
  const candidates = selectCandidates()
  console.log(`Selected ${candidates.length} new candidates from ${subtlex.length} source words.`)

  console.log('Looking up part of speech via WordNet (this takes a few minutes)...')
  const partsOfSpeech = await lookupPartsOfSpeech(candidates.map((c) => c.spelling))

  const words: SeedWord[] = candidates.map((c, i) => ({
    spelling: c.spelling,
    frequencyScore: frequencyScoreFor(i, candidates.length),
    partOfSpeech: partsOfSpeech[i],
  }))

  writeOutput(words)

  const posCounts = new Map<string, number>()
  for (const w of words) posCounts.set(w.partOfSpeech, (posCounts.get(w.partOfSpeech) ?? 0) + 1)
  console.log('\nPart-of-speech breakdown:', Object.fromEntries(posCounts))
  console.log(`\nWrote ${words.length} words to content-engine/words/bulkSeedWords.ts`)
  console.log(`New total word bank size: ${SEED_WORDS.length + words.length}`)
}

main().catch((err) => {
  console.error('expandWordBank failed:', err)
  process.exit(1)
})
