// Tags the word bank into semantic categories using an LLM, in batch, offline.
//
// Why AI here specifically: category membership is the one thing about a word
// that can't be derived from its spelling, and the existing WordNet/Datamuse
// pipeline only reached 227 of 15,000 words across 7 categories. Everything
// else in this project's generation path stays deterministic — this runs once,
// writes a data file, and is never on the critical path of serving a puzzle.
//
// Writes content-engine/words/aiTags.ts. That file is SEPARATE from
// tagOverrides.ts on purpose: tagOverrides is human-reviewed and wins on
// conflict, so re-running this can never clobber a reviewed decision.
//
// Run with: npm run content:tag-words-ai -- [--limit N] [--dry]

import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { GoogleGenAI, Type } from '@google/genai'
import { buildTaggingPrompt, parseTaggingResponse, toTagRecord, type TaggedWord } from '../words/aiTagging'
import { CATEGORY_IDS } from '../words/categories'
import { TAG_OVERRIDES } from '../words/tagOverrides'
import { buildWordBank } from '../words/wordBank'

const MODEL = process.env.GEMINI_MODEL ?? 'gemini-3.5-flash-lite'
const BATCH_SIZE = 60
const MAX_RETRIES = 4
const DRY_RUN = process.argv.includes('--dry')
const LIMIT = (() => {
  const i = process.argv.indexOf('--limit')
  return i === -1 ? Infinity : Number(process.argv[i + 1]) || Infinity
})()

const RESPONSE_SCHEMA = {
  type: Type.ARRAY,
  items: {
    type: Type.OBJECT,
    properties: {
      word: { type: Type.STRING },
      categories: { type: Type.ARRAY, items: { type: Type.STRING, enum: [...CATEGORY_IDS] } },
    },
    required: ['word', 'categories'],
  },
}

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY ?? '' })

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function tagBatch(words: string[]): Promise<TaggedWord[]> {
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: MODEL,
        contents: buildTaggingPrompt(words),
        config: { responseMimeType: 'application/json', responseSchema: RESPONSE_SCHEMA },
      })
      return parseTaggingResponse(JSON.parse(response.text ?? '[]'), words)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      // Rate limits are expected on a 200-request run — back off and retry
      // rather than losing the batch. Anything else gets one retry then is
      // skipped, since one bad batch shouldn't abort hours of work.
      const isRateLimit = message.includes('429') || message.toLowerCase().includes('quota')
      if (attempt === MAX_RETRIES) {
        console.warn(`  batch failed after ${MAX_RETRIES} retries: ${message.slice(0, 120)}`)
        return []
      }
      await sleep(isRateLimit ? 5000 * (attempt + 1) : 1000)
    }
  }
  return []
}

function writeOutput(record: Record<string, string[]>): void {
  const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b))
  const lines = [
    '// AUTO-GENERATED by content-engine/scripts/tagWordsAi.ts — do not hand-edit.',
    '// Machine-assigned semantic category tags. Re-run `npm run content:tag-words-ai`',
    '// to regenerate. Human-reviewed tags live in tagOverrides.ts and take',
    '// precedence over anything here, so regenerating can never lose a reviewed',
    '// decision — correct a bad tag by adding the word to tagOverrides.ts.',
    '',
    'export const AI_TAGS: Record<string, string[]> = {',
    ...entries.map(([word, tags]) => `  ${JSON.stringify(word)}: ${JSON.stringify(tags)},`),
    '}',
    '',
  ]
  writeFileSync(join(process.cwd(), 'content-engine', 'words', 'aiTags.ts'), lines.join('\n'))
}

async function main() {
  if (!process.env.GEMINI_API_KEY) {
    console.error('GEMINI_API_KEY is not set — add it to .env (see .env.example).')
    process.exit(1)
  }

  // Only nouns and adjectives can plausibly be category members; verbs and
  // adverbs are ~2,600 words of guaranteed misses. Words already carrying a
  // human-reviewed tag are skipped entirely — that decision stands.
  const bank = buildWordBank()
  const candidates = bank
    .filter((w) => w.partOfSpeech === 'noun' || w.partOfSpeech === 'adjective')
    .filter((w) => !TAG_OVERRIDES[w.spelling])
    .map((w) => w.spelling)
    .slice(0, LIMIT)

  const batches = Math.ceil(candidates.length / BATCH_SIZE)
  console.log(
    `Tagging ${candidates.length} of ${bank.length} words (nouns/adjectives, minus ${
      Object.keys(TAG_OVERRIDES).length
    } already human-reviewed) in ${batches} batches of ${BATCH_SIZE} via ${MODEL}.`
  )

  const started = Date.now()
  const tagged: TaggedWord[] = []
  for (let i = 0; i < candidates.length; i += BATCH_SIZE) {
    const batch = candidates.slice(i, i + BATCH_SIZE)
    tagged.push(...(await tagBatch(batch)))
    const done = Math.min(i + BATCH_SIZE, candidates.length)
    if ((i / BATCH_SIZE) % 10 === 0 || done === candidates.length) {
      const rate = done / ((Date.now() - started) / 1000)
      console.log(
        `  ${done}/${candidates.length} words, ${tagged.length} tagged so far (${rate.toFixed(0)} words/s)`
      )
    }
  }

  const counts = new Map<string, number>()
  for (const t of tagged) for (const c of t.categories) counts.set(c, (counts.get(c) ?? 0) + 1)
  console.log(`\nTagged ${tagged.length} words. Per-category counts (before parent expansion):`)
  for (const [c, n] of [...counts.entries()].sort((a, b) => b[1] - a[1])) {
    console.log(`  ${c.padEnd(14)} ${String(n).padStart(5)}${n < 25 ? '   (below the 25-word rule floor)' : ''}`)
  }
  for (const id of CATEGORY_IDS) if (!counts.has(id)) console.log(`  ${id.padEnd(14)}     0   (below the 25-word rule floor)`)

  if (DRY_RUN) {
    // Counts alone can't show whether the tags are RIGHT. Print the actual
    // assignments per category so a human can spot a wrong one before a full
    // run commits them.
    console.log('\nSample assignments per category:')
    const byCategory = new Map<string, string[]>()
    for (const t of tagged) {
      for (const c of t.categories) byCategory.set(c, [...(byCategory.get(c) ?? []), t.word])
    }
    for (const [c, words] of [...byCategory.entries()].sort((a, b) => b[1].length - a[1].length)) {
      console.log(`  ${c.padEnd(13)} ${words.slice(0, 18).join(', ')}`)
    }
    console.log('\n--dry: nothing written.')
    process.exit(0)
  }
  writeOutput(toTagRecord(tagged))
  console.log('\nWrote content-engine/words/aiTags.ts')
  console.log('Next: npm run content:build-rule-params to promote categories that clear the floor.')
  process.exit(0)
}

main().catch((err) => {
  console.error('tagWordsAi failed:', err)
  process.exit(1)
})
